# navml: generated
"""The merged surface of ``navigator.widgets.shell.environment_dialog.environment_dialog``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navml.widgets.dialog.button import Button
from navml.widgets.dialog.dialog import Dialog
from navml.widgets.dialog.field import Field
from navml.widgets.dialog.label import Label
from navml.widgets.dialog.list_viewer import ListViewer

from typing import Any, Mapping
from navkit.events import Event
from navkit.i18n import tr
from navkit.reactive import effect
from navigator.environ import valid_name


class EnvironmentDialog(Dialog, _Component):
    names_caption: Label
    names: ListViewer
    value: Field
    pick: Button
    rename: Button
    append: Button
    delete: Button
    abandon: Button
    def __init__(self, variables: Mapping[str, str] | None = ..., **kwargs: Any) -> None: ...
    async def on_abandon_click(self, event: _Event) -> bool: ...
    def mounted(self) -> None: ...
    buttons_row: tuple[Any, ...]
    def _refresh(self, cursor: int) -> None: ...
    def _keep_value(self) -> None: ...
    def _show(self, index: int) -> None: ...
    def _follow_cursor(self) -> None: ...
    def accept(self) -> dict[str, str]: ...
    async def on_pick_click(self, event: Event) -> bool: ...
    async def on_append_click(self, event: Event) -> bool: ...
    async def append_variable(self) -> None: ...
    async def on_rename_click(self, event: Event) -> bool: ...
    async def rename_variable(self) -> None: ...
    async def on_delete_click(self, event: Event) -> bool: ...
    async def delete_variable(self) -> None: ...
