# navml: generated
"""The merged surface of ``navigator.widgets.shell.shell``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.widgets.clock import Clock
from navigator.widgets.command_line import CommandLine
from navigator.widgets.console import Console
from navigator.widgets.keybar import KeyBar
from navigator.widgets.main_menu import MainMenu
from navml.widgets.desktop import Desktop
from navml.widgets.layout.dock_layout import DockLayout

from pathlib import Path
from typing import Any
from navkit.commands import Command
from navkit.events import Event, KeyEvent
from navkit.reactive import computed
from navkit.screen import Surface
from navkit.stylesheet import Stylesheet
from navml.commands import OpenMenu
from navml.history import HISTORY
from navigator.commands import About, CommandLineEnd, CommandLineHome
from navigator.commands import ExecuteCommandLine, NewManager, OpenTreeWindow
from navigator.subshell import CommandFinished
from navigator.widgets.command_line.command_line import HISTORY_ID
from navigator.scheme import default_scheme
from navigator.widgets.manager import Manager


class Shell(DockLayout, _Component):
    console_visible: bool
    menu: MainMenu
    clock: Clock
    console: Console
    desktop: Desktop
    keybar: KeyBar
    command_line: CommandLine
    def __init__(self, left: Path, right: Path, scheme: Stylesheet | None = ..., **kwargs): ...
    def toggle_console(self) -> None: ...
    def show_console(self) -> None: ...
    async def on_open_menu(self, event: OpenMenu) -> bool: ...
    async def on_key(self, event: KeyEvent) -> bool: ...
    command_prompt: str
    def _command_directory(self) -> Path | None: ...
    def enables(self, command: Command) -> bool: ...
    async def on_command_line_home(self, event: CommandLineHome) -> bool: ...
    async def on_command_line_end(self, event: CommandLineEnd) -> bool: ...
    async def on_execute_command_line(self, event: ExecuteCommandLine) -> bool: ...
    def run_command(self, command: str) -> None: ...
    def _command_finished(self, status: int, cwd: Path | None) -> None: ...
    def command_finished(self, status: int, cwd: Path | None) -> None: ...
    def cursor_position(self) -> tuple[int, int] | None: ...
    active_manager: Manager | None
    async def on_new_manager(self, event: NewManager) -> bool: ...
    async def on_about(self, event: About) -> bool: ...
    async def on_open_tree_window(self, event: OpenTreeWindow) -> bool: ...
    async def on_chosen(self, event: Any) -> bool: ...
    async def on_desktop_opened(self, event: Event) -> bool: ...
    async def on_desktop_emptied(self, event: Event) -> bool: ...
    def render(self, surface: Surface) -> None: ...
