/*
 * The classic DOS Navigator colour scheme.
 *
 * Most of what this file says is what it does not say: a part with no rule of
 * its own inherits the widget that paints it, so the panel title when the
 * panel is idle, the footer, the error line and an ordinary listing row need
 * no declarations at all.  Every one of them used to be a module constant
 * duplicating the panel's own colours.
 *
 * To retheme, do not edit this file -- load another after it that redefines
 * the variables below.  Later definitions win, so a two-line sheet is a whole
 * colour scheme.
 */

$panel-fg:  light_cyan;
$panel-bg:  blue;
$accent-fg: black;
$accent-bg: cyan;

Manager { fg: cyan; bg: black }

Panel                { fg: $panel-fg; bg: $panel-bg; border: single }
Panel:active         { border: double }
Panel:active::title  { fg: $accent-fg; bg: $accent-bg }
Panel::row.directory { fg: white; bold: true }

/* The cursor wins over the directory colour, and turns its bold off again.
   Without that the two rules tie on specificity, so source order settles the
   colours -- but `bold` would survive from the directory rule, because this
   one never mentions it.  That is the one place a per-property cascade
   differs from picking a single winning rule outright. */
Panel::row:selected  { fg: $accent-fg; bg: $accent-bg; bold: false }

MenuBar         { fg: $accent-fg; bg: $accent-bg }
MenuBar::hotkey { fg: red }

KeyBar          { fg: $accent-fg; bg: $accent-bg }
KeyBar::number  { fg: white; bg: black }
