# navml: generated
"""The merged surface of ``navml.widgets.list_viewer.list_viewer``."""

from typing import Any as _Any

from navml.component import Component as _Component
from navml.widgets.control import Control

from typing import Any
from navkit.events import KeyEvent, MouseClickEvent
from navkit.reactive import computed, effect, peek, reactive
from navkit.screen import Surface
from navkit.style import Style


class ListViewer(Control, _Component):
    items: _Any
    cursor: int
    scroll: int
    header: int
    error: str | None
    parts: _Any
    def __init__(self, **kwargs: _Any) -> None: ...
    def mounted(self) -> None: ...
    rows: int
    selected: Any
    def _clamp_cursor(self) -> None: ...
    def _follow_cursor(self) -> None: ...
    def move_cursor(self, delta: int) -> None: ...
    def page(self) -> int: ...
    async def choose(self) -> bool: ...
    def row_text(self, index: int, item: Any) -> str: ...
    def row_selected(self, index: int) -> bool: ...
    def row_style(self, index: int, item: Any) -> Style: ...
    def render_row(self, surface: Surface, y: int, index: int, item: Any) -> None: ...
    def title_text(self) -> str: ...
    def footer_text(self) -> str: ...
    async def on_key(self, event: KeyEvent) -> bool: ...
    def row_at(self, y: int) -> int | None: ...
    async def on_mouse_click(self, event: MouseClickEvent) -> bool: ...
    async def on_double_click(self, event: MouseClickEvent) -> bool: ...
    def render(self, surface: Surface) -> None: ...
    def render_header(self, surface: Surface) -> None: ...
    def _render_label(self, surface: Surface, y: int, text: str, part: str) -> None: ...
