# navml: generated
"""The merged surface of ``navigator.widgets.manager.manager.manager``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.widgets.manager.commands import ArchiveFiles, Calculator, ChangeAttributes, ChangeDirectory
from navigator.widgets.manager.commands import ChangeDrive, ChangeLeft, ChangeRight, CompareDir, Copy, CountLength, Delete, DeleteSingle, DiskInfo, Edit
from navigator.widgets.manager.commands import EditNamed, ExtractArchive, FastRename, FindFile, HideInactive
from navigator.widgets.manager.commands import InvertSelection, MakeDirectory, MakeLink, MakeList, PanelSetup
from navigator.widgets.manager.commands import PrintFile, QuickView, RenameMove, Rescan
from navigator.widgets.manager.commands import SelectGroup, SortBy, SwapPanels, SwitchPanel
from navigator.widgets.manager.commands import ToggleHidden, ToggleMark, ToggleShowMode, ToggleTree
from navigator.widgets.manager.commands import UnselectGroup, UserMenu, View
from navigator.widgets.shell.commands import InsertName, InsertPath, ToggleMarkBySpace
from navml.widgets.dialog.commands import QuickSearch
from navigator.widgets.tree.directory_tree import DirectoryTree
from navigator.widgets.viewer.quick_viewer import QuickViewer
from navigator.widgets.manager.panel import Panel
from navml.widgets.layout.horizontal_layout import HorizontalLayout
from navml.widgets.menu.menu_item import MenuItem
from navml.widgets.menu.menu_line import MenuLine
from navml.widgets.menu.sub_menu import SubMenu
from navml.widgets.window import Window

import asyncio
import os
import shlex
from pathlib import Path
from typing import Any, Awaitable, Callable, Sequence
from navkit.reactive import computed, effect, reactive, untracked
from navml.widgets.dialog.dialog import Dialog
from navigator.widgets.manager.commands import ChangeAttributes, ChangeDirectory, ChangeDrive, ChangeLeft, ChangeRight, Copy, Delete, DeleteSingle, Edit, EditNamed, GoParent, HideInactive, HideLeft, HideRight, InvertSelection, MakeDirectory, MakeLink, PrintFile, QuickView, RenameMove, Rescan, ScrollNames, SelectGroup, SwitchPanel, CompareDir, CountLength, SortBy, SwapPanels, ToggleHidden, ToggleMark, ToggleShowMode, ToggleTree, UnselectGroup, View, ViewAsHex, ViewAsText
from navigator.commands import ToggleConsole
from navigator.widgets.file_ops.mkdir_dialog import MkdirDialog
from navigator.widgets.manager.panel.panel import SORT_MODES
from navigator.file_history import open_editor, open_viewer
from navigator.settings import SETTINGS


class Manager(Window, _Component):
    panels: HorizontalLayout
    left: Panel
    right: Panel
    tree: DirectoryTree
    quick: QuickViewer
    panel_menu: SubMenu
    replaced: Any
    replacement: Any
    _last_panel: Any
    hidden_side: Any
    framed: _Any
    keys: _Any
    LOCATE_DELAY: _Any
    def __init__(self, left: Path, right: Path, **kwargs): ...
    async def on_left_execute_file(self, event: _Event) -> bool: ...
    async def on_right_execute_file(self, event: _Event) -> bool: ...
    def mounted(self) -> None: ...
    async def on_switch_panel(self, event: SwitchPanel) -> bool: ...
    async def on_hide_left(self, event: HideLeft) -> bool: ...
    async def on_hide_right(self, event: HideRight) -> bool: ...
    async def on_count_length(self, event: CountLength) -> bool: ...
    async def count_length(self, panel: Panel) -> None: ...
    async def on_compare_dir(self, event: CompareDir) -> bool: ...
    async def compare_directories(self) -> None: ...
    async def on_swap_panels(self, event: SwapPanels) -> bool: ...
    async def on_hide_inactive(self, event: HideInactive) -> bool: ...
    async def on_rescan(self, event: Rescan) -> bool: ...
    async def on_change_directory(self, event: ChangeDirectory) -> bool: ...
    async def on_change_left(self, event: ChangeLeft) -> bool: ...
    async def on_change_right(self, event: ChangeRight) -> bool: ...
    async def on_change_drive(self, event: ChangeDrive) -> bool: ...
    def bring_side(self, side: str) -> Panel: ...
    async def choose_bookmark(self, panel: Panel) -> None: ...
    async def change_directory(self) -> None: ...
    def enables(self, command: Any) -> bool: ...
    def checks(self, command: Any) -> bool | None: ...
    def _command_line_has_text(self) -> bool: ...
    async def on_scroll_names(self, event: ScrollNames) -> bool: ...
    async def on_go_parent(self, event: GoParent) -> bool: ...
    async def on_toggle_mark(self, event: ToggleMark) -> bool: ...
    async def on_invert_selection(self, event: InvertSelection) -> bool: ...
    async def on_select_group(self, event: SelectGroup) -> bool: ...
    async def on_unselect_group(self, event: UnselectGroup) -> bool: ...
    async def select_group(self, *, select: bool, invert: bool) -> None: ...
    async def on_toggle_show_mode(self, event: ToggleShowMode) -> bool: ...
    async def on_sort_by(self, event: SortBy) -> bool: ...
    async def choose_sort(self, panel: Panel) -> None: ...
    async def on_toggle_hidden(self, event: ToggleHidden) -> bool: ...
    async def on_quick_search(self, event: QuickSearch) -> bool: ...
    async def on_toggle_tree(self, event: ToggleTree) -> bool: ...
    async def on_quick_view(self, event: QuickView) -> bool: ...
    async def on_tree_chosen(self, event: Any) -> bool: ...
    async def on_make_directory(self, event: MakeDirectory) -> bool: ...
    async def make_directory(self) -> None: ...
    def selection(self, panel: Panel) -> list[Any]: ...
    async def on_print_file(self, event: PrintFile) -> bool: ...
    async def print_files(self) -> None: ...
    async def on_copy(self, event: Copy) -> bool: ...
    async def on_rename_move(self, event: RenameMove) -> bool: ...
    async def copy_files(self, *, move: bool) -> None: ...
    async def _watch_copy(self, work: asyncio.Future[Any], job: Any, move: bool) -> None: ...
    async def _watch_job(self, work: asyncio.Future[Any], job: Any, make_box: Callable[[], Any], refresh: Callable[[Any], None], answer: Callable[[Any], Awaitable[Any]]) -> None: ...
    async def _ask_yes_no(self, prompt: str, title: str = ...) -> Any: ...
    async def _answer_copy_question(self, question: Any) -> Any: ...
    async def _ask_skip(self, message: str) -> bool: ...
    async def on_delete(self, event: Delete) -> bool: ...
    async def on_delete_single(self, event: DeleteSingle) -> bool: ...
    async def delete_files(self, *, single: bool) -> None: ...
    async def _answer_erase_question(self, question: Any) -> Any: ...
    async def on_make_link(self, event: MakeLink) -> bool: ...
    async def make_links(self) -> None: ...
    async def on_change_attributes(self, event: ChangeAttributes) -> bool: ...
    async def change_attributes(self) -> None: ...
    async def on_view(self, event: View) -> bool: ...
    async def on_view_as_text(self, event: ViewAsText) -> bool: ...
    async def on_view_as_hex(self, event: ViewAsHex) -> bool: ...
    async def view(self, mode: str | None = ...) -> None: ...
    async def on_edit(self, event: Edit) -> bool: ...
    def run_external(self, variable: str, fallback: str, path: Path | None = ...) -> None: ...
    async def on_edit_named(self, event: EditNamed) -> bool: ...
    async def edit_named(self) -> None: ...
    async def edit(self) -> None: ...
    def _remember_panel(self) -> None: ...
    active_panel: Panel
    passive_panel: Panel
    def list_name(self) -> str: ...
    def switch_panel(self) -> None: ...
    def side_view(self, side: str) -> Any: ...
    async def toggle_side(self, side: str) -> None: ...
    def toggle_inactive_side(self) -> None: ...
    def swap_panels(self) -> None: ...
    def show_only(self, side: str) -> None: ...
    def hide_side(self, side: str) -> None: ...
    def show_side(self, side: str) -> None: ...
    tree_replaces: Any
    def toggle_tree(self) -> None: ...
    def toggle_quick_view(self) -> None: ...
    def switch_view(self, view: Any) -> None: ...
    def _focus_replacement(self) -> None: ...
    def _quick_view_follows_panel(self) -> None: ...
    def _tree_follows_panel(self) -> None: ...
    def _panel_follows_tree(self) -> None: ...
    async def _follow_later(self, path: Path) -> None: ...
