"""Navigator's translations: one ``<code>.toml`` per language, read by
:mod:`navkit.i18n` (see that module for the format)."""


def strings():
    """Tables of captions kept English and passed to ``tr()`` where shown.

    Read rather than marked: the palette's is regenerated by ``palconv.py
    --names``, and the key tables' titles head ``keybindings.ini`` sections.
    ``python -m navml extract`` asks for them, as ``(key, where)`` pairs.
    """
    from navigator import keybindings, palette

    where = "navigator/palette.py"
    for _, _, group, item in palette.ENTRIES:
        yield group, where
        yield item, where
    yield palette.NAVIGATOR_GROUP, where
    for item in palette.DERIVED_ITEMS.values():
        yield item, where
    for _, title, _ in keybindings.TABLES:
        yield title, "navigator/keybindings.py"
