# navml: generated
"""The merged surface of ``navigator.widgets.viewer.db_window.db_window``."""

from typing import Any as _Any

from navml.component import Component as _Component
from navigator.widgets.viewer.commands import ContinueSearch, EditDbField, SearchAgain, SearchFor, ShowFields, ShowMemo
from navigator.widgets.viewer.db_window.db_viewer import DBViewer
from navml.commands import CloseWindow
from navml.widgets.dialog.static_text import StaticText
from navml.widgets.window import Window

from pathlib import Path
from typing import Any
from navkit.i18n import tr
from navkit.reactive import effect
from navml.widgets.dialog.dialog import Dialog
from navigator import dbf


class DBWindow(Window, _Component):
    viewer: DBViewer
    indicator: StaticText
    def __init__(self, db: dbf.DBFile | None = ..., **kwargs: Any) -> None: ...
    def mounted(self) -> None: ...
    def _follow_cursor(self) -> None: ...
    def list_name(self) -> str: ...
    def close(self) -> None: ...
    async def _say(self, prompt: str, title: str | None = ...) -> None: ...
    async def on_show_fields(self, event: ShowFields) -> bool: ...
    async def on_show_memo(self, event: ShowMemo) -> bool: ...
    async def show_memo(self) -> None: ...
    async def on_edit_db_field(self, event: EditDbField) -> bool: ...
    async def edit_field(self) -> None: ...
    async def on_search_for(self, event: SearchFor) -> bool: ...
    async def on_continue_search(self, event: ContinueSearch) -> bool: ...
    async def on_search_again(self, event: SearchAgain) -> bool: ...
    async def search_for(self) -> None: ...
    async def search_again(self) -> None: ...
    async def _find(self, answer: dict[str, Any], start: int) -> None: ...
