# navml: generated
"""The merged surface of ``navml.widgets.dialog.button.button``."""

from typing import Any as _Any

from navml.component import Component as _Component
from navml.widgets.dialog.control import Control
from navml.widgets.dialog.static_text import StaticText

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any
from navkit.events import Event, KeyEvent, KeyReleaseEvent, MouseClickEvent
from navkit.glyphs import GLYPHS_UNICODE
from navkit.reactive import computed, effect
from navkit.screen import Surface
from navkit.style import Style
from navkit.widget import Widget


class ClickEvent(Event): ...


class Button(Control, _Component):
    text: str
    default: bool
    down: bool
    caption: StaticText
    emits: _Any
    parts: _Any
    def __init__(self, text: str = ..., **kwargs: Any) -> None: ...
    am_default: bool
    marked: bool
    async def press(self) -> bool: ...
    async def activate(self, letter: str = ...) -> bool: ...
    async def on_key(self, event: KeyEvent) -> bool: ...
    async def on_key_release(self, event: KeyReleaseEvent) -> bool: ...
    async def _end_flash(self) -> None: ...
    def _stop_flash(self) -> None: ...
    async def _release(self) -> bool: ...
    async def on_mouse_click(self, event: MouseClickEvent) -> bool: ...
    def mounted(self) -> None: ...
    def _pop_up_on_blur(self) -> None: ...
    def unmounting(self) -> None: ...
    face: tuple[int, int]
    def render(self, surface: Surface) -> None: ...
