# navml: generated
"""The merged surface of ``navigator.widgets.editor.edit_window.edit_window``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.commands import PrintFile
from navigator.widgets.editor.commands import AsciiTable, CalcBlock, SwitchBrackets, SwitchSave, SwitchWrap, FCenter, FJustify, FLeft, FRight, SetMargins, ContSearch, LoadText, Replace, ReverseSearch, StartSearch, SaveAll, SaveTextAs, CapitalizeBlock, Clear, ClipboardCopy, ClipboardCut, ClipboardPaste, CopyBlock, GotoLineNumber, PrintBlock, IndentBlock, InsertDate, InsertTime, BlockRead, BlockWrite, LowcaseBlock, MoveBlock, SaveText, SortBlock, UnindentBlock, Undo, UpcaseBlock, SwitchBlock
from navigator.widgets.editor.file_editor import FileEditor, InfoLine
from navml.commands import CloseWindow
from navml.widgets.dialog.scroll_bar import ScrollBar
from navml.widgets.menu.menu_item import MenuItem
from navml.widgets.menu.menu_line import MenuLine
from navml.widgets.menu.sub_menu import SubMenu
from navml.widgets.window import Window

import asyncio
import os
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from navkit.events import Event
from navml.widgets.dialog.dialog import Dialog
from navml.widgets.dialog.scroll_bar import ScrollEvent
from navigator.editor.document import decode, encode
from navigator.editor.save import write_file
from navigator.file_history import place_window, window_values
from navigator.models.edit_record import EditRecord
from navigator.settings import SETTINGS


class FileSaved(Event): ...


class EditWindow(Window, _Component):
    editor: FileEditor
    vbar: ScrollBar
    hbar: ScrollBar
    info: InfoLine
    edit_menu: SubMenu
    edit_menu_file: SubMenu
    edit_menu_edit: SubMenu
    edit_menu_search: SubMenu
    edit_menu_paragraph: SubMenu
    edit_menu_block: SubMenu
    edit_menu_misc: SubMenu
    edit_menu_misc_uppercase: SubMenu
    edit_menu_misc_lowercase: SubMenu
    edit_menu_misc_capitalize: SubMenu
    edit_menu_options: SubMenu
    emits: _Any
    _replace_all: _Any
    def __init__(self, path: Path | str, *, new: bool = ..., smartpad: bool = ..., **kwargs: Any) -> None: ...
    def _title(self) -> str: ...
    def take_keyboard(self) -> None: ...
    def list_name(self) -> str: ...
    def remember_history(self) -> None: ...
    def recall_history(self) -> None: ...
    def close(self) -> None: ...
    async def on_save_text(self, event: SaveText) -> bool: ...
    async def save(self) -> bool: ...
    def enables(self, command: Any) -> bool: ...
    async def _ask_file(self, title: str, label: str, history_id: str, ok_text: str | None = ...) -> Path | None: ...
    async def _block_file(self, title: str, label: str) -> Path | None: ...
    async def _check_for_over(self, path: Path, *, append: bool) -> tuple[bool, int | None] | None: ...
    async def _say(self, message: str) -> None: ...
    async def on_block_write(self, event: BlockWrite) -> bool: ...
    async def write_block(self) -> None: ...
    async def on_block_read(self, event: BlockRead) -> bool: ...
    async def read_block(self) -> None: ...
    async def on_start_search(self, event: StartSearch) -> bool: ...
    async def on_replace(self, event: Replace) -> bool: ...
    async def on_cont_search(self, event: ContSearch) -> bool: ...
    async def on_reverse_search(self, event: ReverseSearch) -> bool: ...
    async def start_search(self, *, replace: bool) -> None: ...
    async def search(self, *, reverse: bool = ..., at: Any = ...) -> bool: ...
    async def on_set_margins(self, event: SetMargins) -> bool: ...
    async def set_margins(self) -> None: ...
    async def on_goto_line_number(self, event: GotoLineNumber) -> bool: ...
    async def goto_line(self) -> None: ...
    async def on_ascii_table(self, event: AsciiTable) -> bool: ...
    async def ascii_table(self) -> None: ...
    async def on_print_block(self, event: PrintBlock) -> bool: ...
    async def print_block(self) -> None: ...
    async def on_print_file(self, event: PrintFile) -> bool: ...
    async def print_file(self) -> None: ...
    async def print_lines(self, lines: list[str]) -> None: ...
    async def on_save_all(self, event: SaveAll) -> bool: ...
    async def save_all(self) -> None: ...
    async def on_load_text(self, event: LoadText) -> bool: ...
    async def load_text(self) -> None: ...
    async def on_save_text_as(self, event: SaveTextAs) -> bool: ...
    async def save_as(self) -> None: ...
    def must_ask(self) -> bool: ...
    async def ask_to_close(self) -> bool: ...
    async def on_vbar_scroll(self, event: ScrollEvent) -> bool: ...
    async def on_hbar_scroll(self, event: ScrollEvent) -> bool: ...
