# navml: generated
"""The merged surface of ``navml.widgets.window.window``."""

from typing import Any as _Any

from navml.component import Component as _Component

from typing import Any
from navkit.events import DoubleClickEvent, KeyEvent, MouseClickEvent
from navkit.glyphs import BOX_CHARSETS
from navkit.reactive import computed
from navkit.screen import Surface
from navkit.stylesheet import StyleProperty
from navkit.widget import Widget


class Window(_Component):
    title: str
    closable: bool
    zoomable: bool
    resizable: bool
    min_width: int
    min_height: int
    zoomed: bool
    framed: bool
    border: _Any
    parts: _Any
    def __init__(self, **kwargs: Any) -> None: ...
    desktop: Any
    active: bool
    def _bounds(self) -> tuple[int, int]: ...
    def layout(self, width: int, height: int) -> None: ...
    def _clamp(self, width: int, height: int) -> None: ...
    def move_to(self, x: int, y: int) -> None: ...
    def resize_to(self, width: int, height: int) -> None: ...
    def toggle_zoom(self) -> None: ...
    def _icons(self) -> dict[str, int]: ...
    def _has_grip(self) -> bool: ...
    def chrome_hit(self, x: int, y: int) -> str | None: ...
    def render(self, surface: Surface) -> None: ...
    def render_after(self, surface: Surface) -> None: ...
    def _paint_chrome(self, surface: Surface) -> None: ...
    def close(self) -> None: ...
    async def dispatch_mouse(self, event: MouseClickEvent) -> bool: ...
    def _press_chrome(self, local: MouseClickEvent) -> bool: ...
    def _start_drag(self, kind: str, local: MouseClickEvent) -> None: ...
    async def on_mouse_click(self, event: MouseClickEvent) -> bool: ...
    def _drag_out_of_zoom(self, grab_x: int, event: MouseClickEvent) -> None: ...
    async def on_double_click(self, event: DoubleClickEvent) -> bool: ...
    moving: bool
    def begin_move(self) -> None: ...
    def end_move(self, keep: bool = ...) -> None: ...
    async def on_key(self, event: KeyEvent) -> bool: ...
