# navml: generated
"""The merged surface of ``navml.widgets.dialog.file_dialog.file_dialog``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navml.widgets.dialog.button import Button
from navml.widgets.dialog.dialog import Dialog
from navml.widgets.dialog.field import Field
from navml.widgets.dialog.file_list import FileInfoPane, FileList
from navml.widgets.dialog.label import Label

import os
from pathlib import Path
from typing import Any, Callable
from navkit.events import Event, KeyEvent
from navkit.i18n import tr
from navkit.reactive import effect
from navkit.widget import Widget
from navml.background import Background, Outcome
from navml.history import HISTORY
from navml.widgets.dialog.file_list import scan


class FileDialog(Dialog, _Component):
    caption: Label
    target: Field
    files_caption: Label
    files: FileList
    dirs_caption: Label
    dirs: FileList
    pick: Button
    abandon: Button
    helper: Button
    info: FileInfoPane
    def __init__(self, *, title: str | None = ..., label: str | None = ..., history_id: str = ..., directory: Path | str | None = ..., wildcard: str = ..., hidden: bool = ..., ok_text: str | None = ..., **kwargs: Any) -> None: ...
    async def on_abandon_click(self, event: _Event) -> bool: ...
    async def on_helper_click(self, event: _Event) -> bool: ...
    def mounted(self) -> None: ...
    def read_directory(self, then: Callable[[], None] | None = ...) -> None: ...
    def _follow_lists(self) -> None: ...
    def focusable(self) -> list[Widget]: ...
    buttons_row: tuple[Any, ...]
    async def on_key(self, event: KeyEvent) -> bool: ...
    def file_name(self) -> Path: ...
    def valid(self) -> bool: ...
    def _change_to(self, directory: Path, wildcard: str) -> None: ...
    def _say(self, message: str) -> None: ...
    def record_history(self) -> None: ...
    def accept(self) -> str: ...
    async def on_pick_click(self, event: Event) -> bool: ...
    async def on_files_chosen(self, event: Any) -> bool: ...
    async def on_dirs_chosen(self, event: Any) -> bool: ...
