# navml: generated
"""The merged surface of ``navigator.widgets.viewer.file_window.file_window``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.widgets.viewer.commands import AddFilter, ChooseEncoding, CloseViewer, ContinueSearch, GotoAddress, HexMode, SaveViewAs
from navigator.widgets.viewer.commands import ReverseSearch, SearchAgain, SearchFor, SetViewFilter, SetViewMode, Unwrap
from navigator.widgets.editor.commands import SwitchHighLight
from navigator.widgets.viewer.file_viewer import FileViewer
from navml.commands import CloseWindow
from navml.widgets.dialog.scroll_bar import ScrollBar
from navml.widgets.dialog.static_text import StaticText
from navml.widgets.menu.menu_item import MenuItem
from navml.widgets.menu.menu_line import MenuLine
from navml.widgets.menu.sub_menu import SubMenu
from navml.widgets.window import Window

from pathlib import Path
from typing import Any
from navkit.commands import Command
from navkit.events import DoubleClickEvent
from navkit.i18n import tr
from navml.widgets.dialog.dialog import Dialog
from navml.widgets.dialog.scroll_bar import ScrollEvent
import navigator.viewer as viewer_model
from navigator.file_history import place_window, window_values
from navigator.models.view_record import ViewRecord
from navigator.progress import run_with_progress
from navigator.viewer import SearchJob, ViewSearch
from navigator.settings import SETTINGS
from navigator.widgets.viewer.file_viewer.file_viewer import FILTER_TAGS, MODES


class FileWindow(Window, _Component):
    viewer: FileViewer
    bar: ScrollBar
    info: StaticText
    view_menu: SubMenu
    def __init__(self, path: Path | str, *, mode: str | None = ..., source: Any = ..., **kwargs: Any) -> None: ...
    def take_keyboard(self) -> None: ...
    def list_name(self) -> str: ...
    def remember_history(self) -> None: ...
    def recall_history(self, *, keep_mode: bool = ...) -> None: ...
    def close(self) -> None: ...
    async def on_close_viewer(self, event: CloseViewer) -> bool: ...
    async def on_unwrap(self, event: Unwrap) -> bool: ...
    async def on_switch_high_light(self, event: SwitchHighLight) -> bool: ...
    async def on_hex_mode(self, event: HexMode) -> bool: ...
    async def on_add_filter(self, event: AddFilter) -> bool: ...
    async def on_set_view_mode(self, event: SetViewMode) -> bool: ...
    async def on_set_view_filter(self, event: SetViewFilter) -> bool: ...
    def checks(self, command: Command) -> bool | None: ...
    def enables(self, command: Command) -> bool: ...
    async def on_bar_scroll(self, event: ScrollEvent) -> bool: ...
    async def on_double_click(self, event: DoubleClickEvent) -> bool: ...
    async def on_goto_address(self, event: GotoAddress) -> bool: ...
    async def goto_address(self) -> None: ...
    async def on_save_view_as(self, event: SaveViewAs) -> bool: ...
    async def on_choose_encoding(self, event: ChooseEncoding) -> bool: ...
    async def choose_encoding(self) -> None: ...
    async def save_as(self) -> None: ...
    async def on_search_for(self, event: SearchFor) -> bool: ...
    async def on_continue_search(self, event: ContinueSearch) -> bool: ...
    async def on_search_again(self, event: SearchAgain) -> bool: ...
    async def on_reverse_search(self, event: ReverseSearch) -> bool: ...
    async def search_for(self) -> None: ...
    async def search_again(self, *, reverse: bool) -> None: ...
    async def search(self, search: ViewSearch, backward: bool) -> None: ...
