# navml: generated
"""The merged surface of ``navigator.widgets.viewer.file_window.file_window``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.commands import AddFilter, CloseViewer, ContinueSearch, GotoAddress, HexMode
from navigator.commands import ReverseSearch, SearchAgain, SearchFor, SetViewFilter, SetViewMode, Unwrap
from navigator.widgets.viewer.file_viewer import FileViewer
from navml.commands import CloseWindow
from navml.widgets.dialog.scroll_bar import ScrollBar
from navml.widgets.dialog.static_text import StaticText
from navml.widgets.menu.menu_item import MenuItem
from navml.widgets.menu.menu_line import MenuLine
from navml.widgets.menu.sub_menu import SubMenu
from navml.widgets.window import Window

import asyncio
from pathlib import Path
from typing import Any
from navkit.commands import Command
from navkit.events import DoubleClickEvent
from navml.widgets.dialog.dialog import Dialog
from navml.widgets.dialog.scroll_bar import ScrollEvent
import navigator.viewer as viewer_model
from navigator.viewer import SearchJob, ViewSearch


class FileWindow(Window, _Component):
    viewer: FileViewer
    bar: ScrollBar
    info: StaticText
    view_menu: SubMenu
    def __init__(self, path: Path | str, *, mode: str = ..., **kwargs: Any) -> None: ...
    def take_keyboard(self) -> None: ...
    def list_name(self) -> str: ...
    async def on_close_viewer(self, event: CloseViewer) -> bool: ...
    async def on_unwrap(self, event: Unwrap) -> bool: ...
    async def on_hex_mode(self, event: HexMode) -> bool: ...
    async def on_add_filter(self, event: AddFilter) -> bool: ...
    async def on_set_view_mode(self, event: SetViewMode) -> bool: ...
    async def on_set_view_filter(self, event: SetViewFilter) -> bool: ...
    def checks(self, command: Command) -> bool | None: ...
    def enables(self, command: Command) -> bool: ...
    async def on_bar_scroll(self, event: ScrollEvent) -> bool: ...
    async def on_double_click(self, event: DoubleClickEvent) -> bool: ...
    async def on_goto_address(self, event: GotoAddress) -> bool: ...
    async def goto_address(self) -> None: ...
    async def on_search_for(self, event: SearchFor) -> bool: ...
    async def on_continue_search(self, event: ContinueSearch) -> bool: ...
    async def on_search_again(self, event: SearchAgain) -> bool: ...
    async def on_reverse_search(self, event: ReverseSearch) -> bool: ...
    async def search_for(self) -> None: ...
    async def search_again(self, *, reverse: bool) -> None: ...
    async def search(self, search: ViewSearch, backward: bool) -> None: ...
    async def _watch(self, work: asyncio.Future[Any], job: SearchJob, total: int) -> None: ...
