# navml: generated
"""The merged surface of ``navigator.widgets.manager.manager``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.commands import ChangeDirectory, Copy, Delete, Edit, MakeDirectory, RenameMove
from navigator.commands import Rescan, SwitchPanel, ToggleTree, UserMenu, View
from navigator.commands import ArchiveFiles, Calculator, ChangeDrive, DeleteSingle, DiskInfo, EditNamed
from navigator.commands import ExtractArchive, FastRename, FindFile, MakeList, PanelSetup
from navigator.commands import PhoneBook, PrintFile, QuickView, Reanimate, SortBy, SplitCombine
from navigator.commands import InsertName, InsertPath, ToggleDescriptions, ToggleShowMode
from navigator.widgets.directory_tree import DirectoryTree
from navigator.widgets.quick_viewer import QuickViewer
from navigator.widgets.panel import Panel
from navml.widgets.layout.horizontal_layout import HorizontalLayout
from navml.widgets.window import Window

import asyncio
from pathlib import Path
from typing import Any
from navkit.reactive import computed, effect, reactive, untracked
from navml.widgets.dialog.dialog import Dialog
from navigator.commands import ChangeDirectory, MakeDirectory, QuickView, Rescan, SwitchPanel, ToggleTree, View, ViewAsHex, ViewAsText
from navigator.widgets.mkdir_dialog import MkdirDialog


class Manager(Window, _Component):
    panels: HorizontalLayout
    left: Panel
    right: Panel
    tree: DirectoryTree
    quick: QuickViewer
    replaced: Any
    replacement: Any
    _last_panel: Any
    framed: _Any
    LOCATE_DELAY: _Any
    def __init__(self, left: Path, right: Path, **kwargs): ...
    async def on_left_execute_file(self, event: _Event) -> bool: ...
    async def on_right_execute_file(self, event: _Event) -> bool: ...
    def mounted(self) -> None: ...
    async def on_switch_panel(self, event: SwitchPanel) -> bool: ...
    async def on_rescan(self, event: Rescan) -> bool: ...
    async def on_change_directory(self, event: ChangeDirectory) -> bool: ...
    async def change_directory(self) -> None: ...
    async def on_toggle_tree(self, event: ToggleTree) -> bool: ...
    async def on_quick_view(self, event: QuickView) -> bool: ...
    async def on_tree_chosen(self, event: Any) -> bool: ...
    async def on_make_directory(self, event: MakeDirectory) -> bool: ...
    async def make_directory(self) -> None: ...
    async def on_view(self, event: View) -> bool: ...
    async def on_view_as_text(self, event: ViewAsText) -> bool: ...
    async def on_view_as_hex(self, event: ViewAsHex) -> bool: ...
    async def view(self, mode: str) -> None: ...
    def _remember_panel(self) -> None: ...
    active_panel: Panel
    def list_name(self) -> str: ...
    def switch_panel(self) -> None: ...
    tree_replaces: Any
    def toggle_tree(self) -> None: ...
    def toggle_quick_view(self) -> None: ...
    def switch_view(self, view: Any) -> None: ...
    def _focus_replacement(self) -> None: ...
    def _quick_view_follows_panel(self) -> None: ...
    def _tree_follows_panel(self) -> None: ...
    def _panel_follows_tree(self) -> None: ...
    async def _follow_later(self, path: Path) -> None: ...
