# navml: generated
"""The merged surface of ``navigator.widgets.game.game_window.game_window``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.widgets.game.commands import GameSetup, LevelUp, NewGame, PauseGame, ShowTopTen, TogglePreview
from navigator.widgets.game.game_window.glass import Glass
from navigator.widgets.game.game_window.info import GameInfo
from navml.commands import CloseWindow
from navml.widgets.dialog.button import Button
from navml.widgets.window import Window

from typing import Any
from navkit.events import Event
from navkit.reactive import effect
from navml.widgets.dialog.dialog import Dialog
from navigator import tetris
from navigator.settings import SETTINGS


class GameWindow(Window, _Component):
    glass: Glass
    info: GameInfo
    new_button: Button
    setup_button: Button
    top_button: Button
    pause_button: Button
    def __init__(self, **kwargs: Any) -> None: ...
    style_name: str
    def mounted(self) -> None: ...
    def unmounting(self) -> None: ...
    def _pause_when_left(self) -> None: ...
    async def _tick(self) -> None: ...
    def _show_best(self) -> None: ...
    def _redraw(self) -> None: ...
    async def _game_over(self) -> None: ...
    async def show_scores(self, highlight: int | None = ...) -> None: ...
    async def setup(self) -> None: ...
    async def on_new_game(self, event: NewGame) -> bool: ...
    async def on_pause_game(self, event: PauseGame) -> bool: ...
    async def on_show_top_ten(self, event: ShowTopTen) -> bool: ...
    async def on_game_setup(self, event: GameSetup) -> bool: ...
    async def on_level_up(self, event: LevelUp) -> bool: ...
    async def on_toggle_preview(self, event: TogglePreview) -> bool: ...
    async def on_new_button_click(self, event: Event) -> bool: ...
    async def on_setup_button_click(self, event: Event) -> bool: ...
    async def on_top_button_click(self, event: Event) -> bool: ...
    async def on_pause_button_click(self, event: Event) -> bool: ...
