# navml: generated
"""The merged surface of ``navml.widgets.input_line.input_line``."""

from typing import Any as _Any

from navml.component import Component as _Component
from navml.widgets.control import Control

from typing import Any
from navkit.events import KeyEvent, MouseClickEvent
from navkit.glyphs import DEFAULT_SCROLLBAR, SCROLLBARS, scrollbar
from navkit.reactive import effect, peek, reactive
from navkit.screen import Surface
from navkit.stylesheet import StyleProperty
from navkit.terminal import CURSOR_SHAPES


class InputLine(Control, _Component):
    value: str
    max_length: int
    cursor: int
    first: int
    anchor: int | None
    caret: _Any
    chars: _Any
    parts: _Any
    def __init__(self, **kwargs: _Any) -> None: ...
    def mounted(self) -> None: ...
    room: int
    def _follow_cursor(self) -> None: ...
    selection: tuple[int, int]
    def select_all(self) -> None: ...
    def _replace_selection(self, text: str) -> None: ...
    def _move(self, where: int, extend: bool) -> None: ...
    def _word_left(self) -> int: ...
    def _word_right(self) -> int: ...
    async def on_key(self, event: KeyEvent) -> bool: ...
    async def on_mouse_click(self, event: MouseClickEvent) -> bool: ...
    async def activate(self, letter: str = ...) -> bool: ...
    def cursor_position(self) -> tuple[int, int] | None: ...
    def render(self, surface: Surface) -> None: ...
    def _render_arrows(self, surface: Surface, room: int) -> None: ...
