# navml: generated
"""The merged surface of ``navigator.widgets.setup.key_bindings_dialog.key_bindings_dialog``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navml.widgets.dialog.button import Button
from navml.widgets.dialog.dialog import Dialog
from navml.widgets.dialog.label import Label
from navml.widgets.dialog.list_viewer import ListViewer
from navml.widgets.dialog.static_text import StaticText
from navigator.widgets.setup.key_bindings_dialog.binding_list import BindingList

from typing import Any, Mapping, Sequence
from navkit.commands import KeyTableError, key_label
from navkit.events import Event
from navkit.reactive import effect
from navigator.keybindings import Assignment, Entry, Section
from navigator.widgets.setup.key_bindings_dialog.binding_list import keys_text


class KeyBindingsDialog(Dialog, _Component):
    groups_caption: Label
    groups: ListViewer
    bindings_caption: Label
    bindings: BindingList
    detail: StaticText
    rebind: Button
    append: Button
    unbind: Button
    restore: Button
    reset: Button
    pick: Button
    abandon: Button
    def __init__(self, sections: Sequence[Section] = ..., assignments: Mapping[str, Assignment] | None = ..., **kwargs: Any) -> None: ...
    async def on_abandon_click(self, event: _Event) -> bool: ...
    def mounted(self) -> None: ...
    buttons_row: tuple[Any, ...]
    def accept(self) -> dict[str, Assignment]: ...
    section: Section | None
    entry: Entry | None
    def _list(self, group: int) -> None: ...
    def _refresh(self) -> None: ...
    def _follow_group(self) -> None: ...
    def _follow_entry(self) -> None: ...
    def _describe(self) -> None: ...
    def keys_of(self, entry: Entry) -> tuple[str, ...]: ...
    async def _ask(self, prompt: str) -> bool: ...
    async def _refuse(self, prompt: str) -> None: ...
    def _put(self, assignment: Assignment) -> bool: ...
    async def bind_key(self, entry: Entry, spec: str, replace: bool) -> bool: ...
    async def capture(self, replace: bool) -> None: ...
    async def on_rebind_click(self, event: Event) -> bool: ...
    async def on_append_click(self, event: Event) -> bool: ...
    async def on_unbind_click(self, event: Event) -> bool: ...
    async def on_restore_click(self, event: Event) -> bool: ...
    async def on_reset_click(self, event: Event) -> bool: ...
    async def reset_all(self) -> None: ...
    async def on_pick_click(self, event: Event) -> bool: ...
