# navml: generated
"""The merged surface of ``navigator.widgets.shell.shell.shell``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.widgets.shell.clock import Clock
from navigator.widgets.shell.command_line import CommandLine
from navigator.widgets.shell.console import Console
from navigator.widgets.shell.keybar import KeyBar
from navigator.widgets.shell.main_menu import MainMenu
from navml.widgets.desktop import Desktop
from navml.widgets.layout.dock_layout import DockLayout

import os
from pathlib import Path
from typing import TYPE_CHECKING, Any
from navkit.commands import Command
from navkit.events import Event, KeyEvent
from navkit.reactive import bind, computed, effect
from navkit.screen import Surface
from navkit.stylesheet import Stylesheet
from navml.widgets.menu.commands import OpenMenu
from navml.history import HISTORY
from navigator.subshell import CommandFinished, CompletionsReady, HistoryChosen, HistoryReady
from navigator.widgets.manager.commands import HideLeft, HideRight, ToggleMark
from navigator.widgets.shell.commands import About, CommandLineEnd, CommandLineHome, CompleteCommandLine, ExecuteCommandLine, InsertName, InsertPath, NewManager, OpenTreeWindow, ToggleMarkBySpace
from navigator.widgets.shell.command_line.command_line import HISTORY_ID
from navigator.scheme import default_scheme
from navigator.widgets.manager.manager import Manager


class Shell(DockLayout, _Component):
    console_visible: bool
    menu: MainMenu
    clock: Clock
    console: Console
    desktop: Desktop
    keybar: KeyBar
    command_line: CommandLine
    def __init__(self, left: Path, right: Path, scheme: Stylesheet | None = ..., **kwargs): ...
    def toggle_console(self) -> None: ...
    def show_console(self) -> None: ...
    async def on_open_menu(self, event: OpenMenu) -> bool: ...
    async def on_key(self, event: KeyEvent) -> bool: ...
    def _console_is_the_terminal(self) -> bool: ...
    async def _terminal_key(self, event: KeyEvent) -> bool: ...
    def _search_history(self, args: list[str]) -> bool: ...
    def history_chosen(self, text: str) -> None: ...
    def _walk_history(self, step: int) -> None: ...
    def history_ready(self, entries: tuple[str, ...]) -> None: ...
    def _step_history(self, step: int) -> None: ...
    def mounted(self) -> None: ...
    def _front_directory(self) -> Path | None: ...
    def _follow_panel(self) -> None: ...
    command_prompt: str
    command_prompt_cells: tuple
    def _command_directory(self) -> Path | None: ...
    program_has_keys: bool
    def enables(self, command: Command) -> bool: ...
    def _editor_has_keys(self) -> bool: ...
    async def on_file_saved(self, event: FileSaved) -> bool: ...
    async def on_command_line_home(self, event: CommandLineHome) -> bool: ...
    async def on_command_line_end(self, event: CommandLineEnd) -> bool: ...
    async def on_complete_command_line(self, event: CompleteCommandLine) -> bool: ...
    def _ask_completions(self) -> None: ...
    completion_list: Any
    def completions_ready(self, event: CompletionsReady) -> None: ...
    def _complete_word(self, event: CompletionsReady, text: str, *, final: bool) -> None: ...
    def _is_directory(self, text: str) -> bool: ...
    def _open_completions(self, event: CompletionsReady, candidates: list[str]) -> None: ...
    def _show_completions(self, start: int, candidates: list[str]) -> None: ...
    def _close_completions(self) -> None: ...
    async def _type_in_completions(self, event: KeyEvent) -> None: ...
    def _panel_entry(self) -> tuple[Path, Any] | None: ...
    def _insert_entry(self, *, whole: bool) -> None: ...
    async def on_toggle_mark_by_space(self, event: ToggleMarkBySpace) -> bool: ...
    async def on_insert_name(self, event: InsertName) -> bool: ...
    async def on_insert_path(self, event: InsertPath) -> bool: ...
    async def on_execute_file(self, event: Any) -> bool: ...
    async def on_execute_command_line(self, event: ExecuteCommandLine) -> bool: ...
    def run_command(self, command: str) -> None: ...
    def _command_finished(self, status: int, cwd: Path | None) -> None: ...
    def command_finished(self, status: int, cwd: Path | None) -> None: ...
    def cursor_position(self) -> tuple[int, int] | None: ...
    active_manager: Manager | None
    async def on_new_manager(self, event: NewManager) -> bool: ...
    async def on_hide_left(self, event: HideLeft) -> bool: ...
    async def on_hide_right(self, event: HideRight) -> bool: ...
    def show_manager_side(self, side: str) -> None: ...
    async def on_about(self, event: About) -> bool: ...
    async def on_open_tree_window(self, event: OpenTreeWindow) -> bool: ...
    async def on_chosen(self, event: Any) -> bool: ...
    async def on_desktop_opened(self, event: Event) -> bool: ...
    async def on_desktop_emptied(self, event: Event) -> bool: ...
    def render(self, surface: Surface) -> None: ...
