# navml: generated
"""The merged surface of ``navigator.widgets.shell.shell.shell``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navigator.widgets.shell.clock import Clock
from navigator.widgets.shell.command_line import CommandLine
from navigator.widgets.shell.console import Console
from navigator.widgets.shell.keybar import KeyBar
from navigator.widgets.shell.main_menu import MainMenu
from navml.widgets.desktop import Desktop
from navml.widgets.layout.dock_layout import DockLayout

import os
from pathlib import Path
from typing import TYPE_CHECKING, Any
from navkit.commands import Command
from navkit.events import Event, KeyEvent
from navkit.reactive import bind, computed, effect
from navkit.screen import Surface
from navkit.widget import Widget
from navkit.stylesheet import Stylesheet
from navml.widgets.dialog.dialog import Dialog
from navml.widgets.menu.commands import OpenMenu
from navml.history import HISTORY
from navigator.commands import AsciiTable, OpenSmartpad, ScreenGrab, ShowUserScreen
from navigator.subshell import CommandFinished, CompletionsReady, HistoryChosen, HistoryReady
from navigator.widgets.manager.commands import Calculator, HideLeft, HideRight, ToggleMark, UserMenu
from navigator.widgets.shell.commands import About, DriveInfoSetup, CommandLineEnd, CommandLineHome, CompleteCommandLine, EditHistory, EditorDefaults, ExecuteCommandLine, FileManagerDefaults, FileManagerSetup, InsertName, InsertPath, InterfaceSetup, LocalMenuFileEdit, MenuFileEdit, NewManager, OpenTreeWindow, SetupConfirmation, StartupSetup, SystemSetup, ToggleMarkBySpace, ViewHistory
from navigator.widgets.shell.command_line.command_line import HISTORY_ID
from navigator.scheme import default_scheme
from navigator.settings import SETTINGS
from navigator.widgets.manager.manager import Manager


class UserScreenPeek(Widget): ...


class Shell(DockLayout, _Component):
    console_visible: bool
    console: Console
    desktop: Desktop
    menu: MainMenu
    clock: Clock
    keybar: KeyBar
    command_line: CommandLine
    _grabber_told: _Any
    def __init__(self, left: Path, right: Path, scheme: Stylesheet | None = ..., **kwargs): ...
    async def on_screen_grab(self, event: ScreenGrab) -> bool: ...
    async def screen_grab(self) -> None: ...
    async def on_show_user_screen(self, event: ShowUserScreen) -> bool: ...
    async def _peek(self, app: Any) -> None: ...
    def toggle_console(self) -> None: ...
    def relay_terminal(self) -> bool: ...
    def _relayed_input(self, data: bytes) -> bytes: ...
    def end_relay(self, *, follow: bool = ...) -> None: ...
    def show_console(self) -> None: ...
    async def on_open_menu(self, event: OpenMenu) -> bool: ...
    async def on_key(self, event: KeyEvent) -> bool: ...
    def _console_is_the_terminal(self) -> bool: ...
    async def _terminal_key(self, event: KeyEvent) -> bool: ...
    def _search_history(self, args: list[str]) -> bool: ...
    def history_chosen(self, text: str) -> None: ...
    def _walk_history(self, step: int) -> None: ...
    def history_ready(self, entries: tuple[str, ...]) -> None: ...
    def _step_history(self, step: int) -> None: ...
    def mounted(self) -> None: ...
    def _size_histories(self) -> None: ...
    def _choose_clipboard(self) -> None: ...
    def _front_directory(self) -> Path | None: ...
    def _follow_panel(self) -> None: ...
    command_prompt: str
    command_prompt_cells: tuple
    def _command_directory(self) -> Path | None: ...
    program_has_keys: bool
    def enables(self, command: Command) -> bool: ...
    def _editor_has_keys(self) -> bool: ...
    async def on_file_saved(self, event: FileSaved) -> bool: ...
    async def on_command_line_home(self, event: CommandLineHome) -> bool: ...
    async def on_command_line_end(self, event: CommandLineEnd) -> bool: ...
    async def on_complete_command_line(self, event: CompleteCommandLine) -> bool: ...
    def _ask_completions(self) -> None: ...
    completion_list: Any
    def completions_ready(self, event: CompletionsReady) -> None: ...
    def _complete_word(self, event: CompletionsReady, text: str, *, final: bool) -> None: ...
    def _is_directory(self, text: str) -> bool: ...
    def _open_completions(self, event: CompletionsReady, candidates: list[str]) -> None: ...
    def _show_completions(self, start: int, candidates: list[str]) -> None: ...
    def _close_completions(self) -> None: ...
    async def _type_in_completions(self, event: KeyEvent) -> None: ...
    def _panel_entry(self) -> tuple[Path, Any] | None: ...
    def _insert_entry(self, *, whole: bool) -> None: ...
    async def on_toggle_mark_by_space(self, event: ToggleMarkBySpace) -> bool: ...
    async def on_open_smartpad(self, event: OpenSmartpad) -> bool: ...
    async def on_calculator(self, event: Calculator) -> bool: ...
    async def on_user_menu(self, event: UserMenu) -> bool: ...
    async def on_menu_file_edit(self, event: MenuFileEdit) -> bool: ...
    async def on_local_menu_file_edit(self, event: LocalMenuFileEdit) -> bool: ...
    def _menu_directory(self) -> Path: ...
    def _menu_panels(self) -> tuple[Any, Any]: ...
    def _menu_side(panel: Any, list_file: str = ...) -> Any: ...
    async def edit_menu_file(self, path: Path) -> None: ...
    async def user_menu(self, want_global: bool = ...) -> None: ...
    async def run_menu_item(self, menu: Any, entry: Any) -> None: ...
    async def on_ascii_table(self, event: AsciiTable) -> bool: ...
    async def ascii_table(self) -> None: ...
    async def on_insert_name(self, event: InsertName) -> bool: ...
    async def on_insert_path(self, event: InsertPath) -> bool: ...
    async def on_execute_file(self, event: Any) -> bool: ...
    async def on_execute_command_line(self, event: ExecuteCommandLine) -> bool: ...
    def run_command(self, command: str, *, typed: bool = ...) -> None: ...
    def _command_finished(self, status: int, cwd: Path | None) -> None: ...
    def command_finished(self, status: int, cwd: Path | None) -> None: ...
    def _follow_shell(self, cwd: Path | None) -> None: ...
    block_insert: bool
    def cursor_position(self) -> tuple[int, int] | None: ...
    active_manager: Manager | None
    async def on_new_manager(self, event: NewManager) -> bool: ...
    async def on_hide_left(self, event: HideLeft) -> bool: ...
    async def on_hide_right(self, event: HideRight) -> bool: ...
    def show_manager_side(self, side: str) -> None: ...
    async def on_about(self, event: About) -> bool: ...
    async def on_system_setup(self, event: SystemSetup) -> bool: ...
    async def on_startup_setup(self, event: StartupSetup) -> bool: ...
    async def on_interface_setup(self, event: InterfaceSetup) -> bool: ...
    async def on_setup_confirmation(self, event: SetupConfirmation) -> bool: ...
    async def on_editor_defaults(self, event: EditorDefaults) -> bool: ...
    async def on_file_manager_setup(self, event: FileManagerSetup) -> bool: ...
    async def on_drive_info_setup(self, event: DriveInfoSetup) -> bool: ...
    async def on_file_manager_defaults(self, event: FileManagerDefaults) -> bool: ...
    async def setup(self, dialog: Any, *sections: str) -> None: ...
    async def on_view_history(self, event: ViewHistory) -> bool: ...
    async def on_edit_history(self, event: EditHistory) -> bool: ...
    async def file_history(self, kind: str) -> None: ...
    async def on_open_tree_window(self, event: OpenTreeWindow) -> bool: ...
    async def on_chosen(self, event: Any) -> bool: ...
    async def on_desktop_opened(self, event: Event) -> bool: ...
    async def on_desktop_emptied(self, event: Event) -> bool: ...
    def render(self, surface: Surface) -> None: ...
