# navml: generated
"""The merged surface of ``navml.widgets.dialog.dialog.dialog``."""

from typing import Any as _Any

from navkit.events import Event as _Event

from navml.component import Component as _Component
from navml.widgets.dialog.commands import Cancel, Default, SelectNext, SelectPrevious
from navml.widgets.dialog.button import Button
from navml.widgets.layout.horizontal_layout import HorizontalLayout
from navml.widgets.dialog.static_text import StaticText
from navml.widgets.dialog.modal import Modal

import asyncio
from typing import Any
from navkit.application import Application
from navkit.commands import Command
from navkit.events import ClickOutsideEvent, Event
from navkit.reactive import reactive
from navkit.widget import Widget
from navml.widgets.dialog.history import History


class Dialog(Modal, _Component):
    buttons: str
    prompt: str
    close_on_outside_click: bool
    message: StaticText
    row: HorizontalLayout
    ok: Button
    no: Button
    cancel: Button
    info: Button
    result: Any
    def __init__(self, **kwargs: Any) -> None: ...
    async def on_cancel_click(self, event: _Event) -> bool: ...
    async def execute(self, app: Application | None = ...) -> Any: ...
    def close(self, result: Any = ...) -> None: ...
    def accept(self) -> Any: ...
    def valid(self) -> bool: ...
    def must_ask(self) -> bool: ...
    async def ask_to_close(self) -> bool: ...
    def request_close(self) -> None: ...
    async def _close_asking(self) -> None: ...
    def unmounting(self) -> None: ...
    def focusable(self) -> list[Widget]: ...
    async def activate_shortcut(self, letter: str) -> bool: ...
    buttons_row: tuple[Widget, ...]
    default_button: Widget | None
    def enables(self, command: Command) -> bool: ...
    async def on_cancel(self, event: Cancel) -> bool: ...
    async def on_click_outside(self, event: ClickOutsideEvent) -> bool: ...
    async def on_default(self, event: Default) -> bool: ...
    async def on_select_next(self, event: SelectNext) -> bool: ...
    async def on_select_previous(self, event: SelectPrevious) -> bool: ...
    def _application_or_raise(self) -> Application: ...
    async def on_ok_click(self, event: Event) -> bool: ...
    async def on_no_click(self, event: Event) -> bool: ...
    def record_history(self) -> None: ...
    async def on_click(self, event: Event) -> bool: ...
    async def show_info(self, event: Event) -> None: ...
