"""Colour schemes, one per DOS Navigator ``.PAL`` palette.

Every file here is generated by ``tools/palconv.py`` from the ``COLORS``
directory of a DOS Navigator 1.51 distribution, and defines only variables --
the rules that read them are in ``navigator/styles/navigator.nss``.

A package rather than a plain directory so that ``importlib.resources`` finds
it and ``[tool.setuptools.package-data]`` can name it, which is what keeps the
themes in a wheel instead of only in a checkout.
"""
