/*
 * Microsoft DOSSHELL -- DOS Navigator's DOSSHELL.PAL.
 *
 * Generated by tools/palconv.py; edit that, or the .PAL, not this.
 * Load it after navigator.nss, whose rules read the names below:
 *
 *     python -m navigator --theme dosshell
 *
 * This palette reprograms the sixteen VGA colour registers, so the
 * sixteen names are pinned to the values it asks for rather than
 * left to the terminal's own theme.  That is the whole difference
 * between it and a palette that only rearranges attributes.
 */

/* The adapter's colour registers, six bits per channel widened to eight. */
$dn-black: #000000;
$dn-blue: #0000aa;
$dn-green: #00aa00;
$dn-cyan: #1caab2;
$dn-red: #ca0000;
$dn-magenta: #aa00aa;
$dn-brown: #aa5500;
$dn-light_gray: #aaaaaa;
$dn-dark_gray: #555555;
$dn-light_blue: #5555ff;
$dn-light_green: #55ff55;
$dn-light_cyan: #55ffff;
$dn-light_red: #ff3559;
$dn-light_magenta: #ff55ff;
$dn-yellow: #ffff55;
$dn-white: #ffffff;

/* All 144 entries DOS Navigator's Colors dialog exposes, in its groups and
   its order. `>' marks the eight navigator.nss reads today; the rest are one
   rule away from being live, and are carried rather than dropped. */

/* -- Timer --------------------------------------------------------------- */
$desktop-fg: $dn-black;               /*> [  1] Color -- CBackground[1] */
$desktop-bg: $dn-cyan;

/* -- Menus --------------------------------------------------------------- */
$bar-fg: $dn-black;                   /*> [  2] Normal -- CMenuView, CStatusLine[1] */
$bar-bg: $dn-cyan;
$bar-disabled-fg: $dn-light_gray;     /*  [  3] Disabled -- CMenuView, CStatusLine[2] */
$bar-disabled-bg: $dn-cyan;
$bar-key-fg: $dn-white;               /*> [  4] Shortcut -- CMenuView, CStatusLine[3] */
$bar-key-bg: $dn-cyan;
$bar-selected-fg: $dn-white;          /*  [  5] Selected -- CMenuView, CStatusLine[4] */
$bar-selected-bg: $dn-blue;
$bar-selected-disabled-fg: $dn-light_gray;/*  [  6] Selected disabled -- CMenuView, CStatusLine[5] */
$bar-selected-disabled-bg: $dn-blue;
$bar-selected-key-fg: $dn-white;      /*  [  7] Shortcut selected -- CMenuView, CStatusLine[6] */
$bar-selected-key-bg: $dn-blue;

/* -- Dialogs ------------------------------------------------------------- */
$dialog-frame-background-fg: $dn-black;/*  [ 33] Frame/background */
$dialog-frame-background-bg: $dn-cyan;
$dialog-frame-icons-fg: $dn-blue;     /*  [ 34] Frame icons */
$dialog-frame-icons-bg: $dn-cyan;
$dialog-scroll-bar-page-fg: $dn-black;/*  [ 35] Scroll bar page */
$dialog-scroll-bar-page-bg: $dn-cyan;
$dialog-scroll-bar-icons-fg: $dn-cyan;/*  [ 36] Scroll bar icons */
$dialog-scroll-bar-icons-bg: $dn-black;
$dialog-static-text-fg: $dn-black;    /*  [ 37] Static text */
$dialog-static-text-bg: $dn-cyan;
$dialog-label-normal-fg: $dn-black;   /*  [ 38] Label normal */
$dialog-label-normal-bg: $dn-cyan;
$dialog-label-selected-fg: $dn-dark_gray;/*  [ 39] Label selected */
$dialog-label-selected-bg: $dn-cyan;
$dialog-label-shortcut-fg: $dn-red;   /*  [ 40] Label shortcut */
$dialog-label-shortcut-bg: $dn-cyan;
$dialog-button-normal-fg: $dn-black;  /*  [ 41] Button normal */
$dialog-button-normal-bg: $dn-white;
$dialog-button-default-fg: $dn-blue;  /*  [ 42] Button default */
$dialog-button-default-bg: $dn-white;
$dialog-button-selected-fg: $dn-white;/*  [ 43] Button selected */
$dialog-button-selected-bg: $dn-black;
$dialog-button-disabled-fg: $dn-light_gray;/*  [ 44] Button disabled */
$dialog-button-disabled-bg: $dn-white;
$dialog-button-shortcut-fg: $dn-red;  /*  [ 45] Button shortcut */
$dialog-button-shortcut-bg: $dn-white;
$dialog-shortcut-selected-fg: $dn-red;/*  [178] Shortcut selected */
$dialog-shortcut-selected-bg: $dn-black;
$dialog-shortcut-default-fg: $dn-blue;/*  [179] Shortcut default */
$dialog-shortcut-default-bg: $dn-white;
$dialog-button-shadow-fg: $dn-cyan;   /*  [ 46] Button shadow */
$dialog-button-shadow-bg: $dn-cyan;
$dialog-cluster-normal-fg: $dn-black; /*  [ 47] Cluster normal */
$dialog-cluster-normal-bg: $dn-cyan;
$dialog-cluster-selected-fg: $dn-red; /*  [ 48] Cluster selected */
$dialog-cluster-selected-bg: $dn-cyan;
$dialog-cluster-shortcut-fg: $dn-red; /*  [ 49] Cluster shortcut */
$dialog-cluster-shortcut-bg: $dn-cyan;
$dialog-input-normal-fg: $dn-light_gray;/*  [ 50] Input normal */
$dialog-input-normal-bg: $dn-dark_gray;
$dialog-input-selected-fg: $dn-white; /*  [ 51] Input selected */
$dialog-input-selected-bg: $dn-black;
$dialog-input-arrow-fg: $dn-white;    /*  [ 52] Input arrow */
$dialog-input-arrow-bg: $dn-dark_gray;
$dialog-history-button-fg: $dn-black; /*  [ 53] History button */
$dialog-history-button-bg: $dn-light_gray;
$dialog-history-sides-fg: $dn-light_gray;/*  [ 54] History sides */
$dialog-history-sides-bg: $dn-cyan;
$dialog-history-bar-page-fg: $dn-black;/*  [ 55] History bar page */
$dialog-history-bar-page-bg: $dn-light_gray;
$dialog-history-bar-icons-fg: $dn-black;/*  [ 56] History bar icons */
$dialog-history-bar-icons-bg: $dn-light_gray;
$dialog-list-normal-fg: $dn-light_gray;/*  [ 57] List normal */
$dialog-list-normal-bg: $dn-dark_gray;
$dialog-list-focused-fg: $dn-white;   /*  [ 58] List focused */
$dialog-list-focused-bg: $dn-black;
$dialog-list-selected-fg: $dn-white;  /*  [ 59] List selected */
$dialog-list-selected-bg: $dn-dark_gray;
$dialog-list-divider-fg: $dn-blue;    /*  [ 60] List divider */
$dialog-list-divider-bg: $dn-dark_gray;
$dialog-information-pane-fg: $dn-white;/*  [ 61] Information pane */
$dialog-information-pane-bg: $dn-dark_gray;

/* -- Tree ---------------------------------------------------------------- */
$dialog-tree-normal-tree-fg: $dn-black;/*  [104] Normal tree */
$dialog-tree-normal-tree-bg: $dn-cyan;
$dialog-tree-normal-nodes-fg: $dn-black;/*  [105] Normal nodes */
$dialog-tree-normal-nodes-bg: $dn-cyan;
$dialog-tree-selected-node-fg: $dn-white;/*  [106] Selected node */
$dialog-tree-selected-node-bg: $dn-blue;
$dialog-tree-default-node-fg: $dn-yellow;/*  [107] Default node */
$dialog-tree-default-node-bg: $dn-cyan;
$dialog-tree-selected-default-fg: $dn-yellow;/*  [108] Selected default */
$dialog-tree-selected-default-bg: $dn-blue;
$dialog-tree-selected-passive-fg: $dn-cyan;/*  [109] Selected passive */
$dialog-tree-selected-passive-bg: $dn-blue;
$dialog-tree-selected-def-passive-fg: $dn-cyan;/*  [110] Selected def. passive */
$dialog-tree-selected-def-passive-bg: $dn-blue;

/* -- File Manager -------------------------------------------------------- */
$frame-fg: $dn-light_gray;            /*  [ 80] Frame passive -- CDoubleWindow[1] -> CFrame[1,2] */
$frame-bg: $dn-white;
$active-frame-fg: $dn-black;          /*  [ 81] Frame active -- CDoubleWindow[2] -> CFrame[3,4] */
$active-frame-bg: $dn-white;
$frame-icon-fg: $dn-cyan;             /*  [ 82] Frame icons -- CDoubleWindow[3] -> CFrame[5] */
$frame-icon-bg: $dn-white;
$scrollbar-page-fg: $dn-white;        /*  [ 83] Scroll bar page -- CDoubleWindow[4] -> CScrollBar[1] */
$scrollbar-page-bg: $dn-black;
$scrollbar-arrow-fg: $dn-white;       /*  [ 84] Scroll bar icons -- CDoubleWindow[5] -> CScrollBar[2,3] */
$scrollbar-arrow-bg: $dn-black;

/* -- File Panel ---------------------------------------------------------- */
$panel-fg: $dn-black;                 /*> [ 85] Normal text -- CDoubleWindow[6] -> CPanel[1] */
$panel-bg: $dn-white;
$marked-fg: $dn-blue;                 /*  [ 87] Selected text -- CDoubleWindow[8] -> CPanel[3] */
$marked-bg: $dn-white;
$cursor-fg: $dn-white;                /*> [ 88] Normal cursor -- CDoubleWindow[9] -> CPanel[4] */
$cursor-bg: $dn-blue;
$marked-cursor-fg: $dn-light_blue;    /*  [ 89] Selected cursor -- CDoubleWindow[10] -> CPanel[5] */
$marked-cursor-bg: $dn-blue;
$divider-fg: $dn-black;               /*  [ 86] List divider -- CDoubleWindow[7] -> CPanel[2] */
$divider-bg: $dn-white;
$active-title-fg: $dn-white;          /*> [ 90] Directory active -- CDoubleWindow[11] -> CTopView[1] */
$active-title-bg: $dn-blue;
$title-fg: $dn-black;                 /*> [ 91] Directory passive -- CDoubleWindow[12] -> CTopView[2] */
$title-bg: $dn-light_gray;
$column-title-fg: $dn-blue;           /*  [165] Column title -- CDoubleWindow[32] -> CPanel[6] */
$column-title-bg: $dn-white;

/* -- Highlight ----------------------------------------------------------- */
$directory-fg: $dn-blue;              /*> [172] Directories -- CDoubleWindow[33] -> CPanel[7], ttDirectory */
$directory-bg: $dn-white;
$executable-fg: $dn-green;            /*  [173] Executables -- CDoubleWindow[34] -> CPanel[8], ttExec */
$executable-bg: $dn-white;
$archive-fg: $dn-cyan;                /*  [174] Archives -- CDoubleWindow[35] -> CPanel[9], ttArc */
$archive-bg: $dn-white;
$highlight-custom-1-fg: $dn-red;      /*  [175] Custom 1 */
$highlight-custom-1-bg: $dn-white;
$highlight-custom-2-fg: $dn-magenta;  /*  [176] Custom 2 */
$highlight-custom-2-bg: $dn-white;
$highlight-custom-3-fg: $dn-brown;    /*  [177] Custom 3 */
$highlight-custom-3-bg: $dn-white;
$highlight-custom-4-fg: $dn-light_gray;/*  [180] Custom 4 */
$highlight-custom-4-bg: $dn-white;
$highlight-custom-5-fg: $dn-dark_gray;/*  [181] Custom 5 */
$highlight-custom-5-bg: $dn-white;

/* -- Drive Line ---------------------------------------------------------- */
$drive-line-drive-letters-fg: $dn-black;/*  [186] Drive letters */
$drive-line-drive-letters-bg: $dn-white;
$drive-line-drive-selected-fg: $dn-white;/*  [188] Drive selected */
$drive-line-drive-selected-bg: $dn-blue;
$drive-line-frame-fg: $dn-black;      /*  [187] Frame */
$drive-line-frame-bg: $dn-white;

/* -- Info ---------------------------------------------------------------- */
$info-current-file-fg: $dn-black;     /*  [119] Current file */
$info-current-file-bg: $dn-white;
$info-selected-text-fg: $dn-black;    /*  [120] Selected text */
$info-selected-text-bg: $dn-white;
$info-selected-numbers-fg: $dn-blue;  /*  [121] Selected numbers */
$info-selected-numbers-bg: $dn-white;
$info-totals-text-fg: $dn-black;      /*  [122] Totals text */
$info-totals-text-bg: $dn-white;
$info-totals-numbers-fg: $dn-blue;    /*  [123] Totals numbers */
$info-totals-numbers-bg: $dn-white;
$info-free-space-text-fg: $dn-black;  /*  [124] Free space text */
$info-free-space-text-bg: $dn-white;
$info-free-space-numbers-fg: $dn-blue;/*  [125] Free space numbers */
$info-free-space-numbers-bg: $dn-white;

/* -- Tree ---------------------------------------------------------------- */
$tree-normal-tree-fg: $dn-black;      /*  [ 94] Normal tree */
$tree-normal-tree-bg: $dn-white;
$tree-normal-nodes-fg: $dn-black;     /*  [ 95] Normal nodes */
$tree-normal-nodes-bg: $dn-white;
$tree-selected-node-fg: $dn-white;    /*  [ 96] Selected node */
$tree-selected-node-bg: $dn-blue;
$tree-default-node-fg: $dn-blue;      /*  [ 97] Default node */
$tree-default-node-bg: $dn-white;
$tree-selected-default-fg: $dn-yellow;/*  [ 98] Selected default */
$tree-selected-default-bg: $dn-blue;
$tree-selected-passive-fg: $dn-yellow;/*  [ 99] Selected passive */
$tree-selected-passive-bg: $dn-blue;
$tree-selected-def-passive-fg: $dn-yellow;/*  [100] Selected def. passive */
$tree-selected-def-passive-bg: $dn-black;
$tree-info-box-fg: $dn-black;         /*  [101] Info box */
$tree-info-box-bg: $dn-white;

/* -- Quick View ---------------------------------------------------------- */
$quick-view-normal-text-fg: $dn-black;/*  [ 92] Normal text */
$quick-view-normal-text-bg: $dn-white;
$quick-view-selected-text-fg: $dn-white;/*  [ 93] Selected text */
$quick-view-selected-text-bg: $dn-blue;

/* -- Disk Info ----------------------------------------------------------- */
$disk-info-normal-text-fg: $dn-black; /*  [103] Normal text */
$disk-info-normal-text-bg: $dn-cyan;
$disk-info-highlighted-text-fg: $dn-white;/*  [102] Highlighted text */
$disk-info-highlighted-text-bg: $dn-cyan;

/* -- File Viewer --------------------------------------------------------- */
$viewer-frame-passive-fg: $dn-light_gray;/*  [112] Frame passive */
$viewer-frame-passive-bg: $dn-cyan;
$viewer-frame-active-fg: $dn-black;   /*  [113] Frame active */
$viewer-frame-active-bg: $dn-cyan;
$viewer-frame-icons-fg: $dn-blue;     /*  [114] Frame icons */
$viewer-frame-icons-bg: $dn-cyan;
$viewer-scroll-bar-page-fg: $dn-white;/*  [115] Scroll bar page */
$viewer-scroll-bar-page-bg: $dn-black;
$viewer-scroll-bar-icons-fg: $dn-white;/*  [116] Scroll bar icons */
$viewer-scroll-bar-icons-bg: $dn-black;
$viewer-normal-text-fg: $dn-light_cyan;/*  [117] Normal text */
$viewer-normal-text-bg: $dn-black;
$viewer-selected-text-fg: $dn-white;  /*  [118] Selected text */
$viewer-selected-text-bg: $dn-blue;

/* -- Editor/Spreadsheet -------------------------------------------------- */
$editor-frame-passive-fg: $dn-light_gray;/*  [ 70] Frame passive */
$editor-frame-passive-bg: $dn-cyan;
$editor-frame-active-fg: $dn-black;   /*  [ 71] Frame active */
$editor-frame-active-bg: $dn-cyan;
$editor-frame-icons-fg: $dn-blue;     /*  [ 73] Frame icons */
$editor-frame-icons-bg: $dn-cyan;
$editor-frame-title-fg: $dn-white;    /*  [ 72] Frame title */
$editor-frame-title-bg: $dn-blue;
$editor-scroll-bar-page-fg: $dn-white;/*  [ 74] Scroll bar page */
$editor-scroll-bar-page-bg: $dn-black;
$editor-scroll-bar-icons-fg: $dn-white;/*  [ 75] Scroll bar icons */
$editor-scroll-bar-icons-bg: $dn-black;
$editor-normal-text-fg: $dn-black;    /*  [ 76] Normal text */
$editor-normal-text-bg: $dn-white;
$editor-selected-text-fg: $dn-white;  /*  [ 77] Selected text */
$editor-selected-text-bg: $dn-blue;

/* -- Highlight ----------------------------------------------------------- */
$editor-highlight-comments-fg: $dn-blue;/*  [164] Comments */
$editor-highlight-comments-bg: $dn-white;
$editor-highlight-symbols-fg: $dn-green;/*  [189] Symbols */
$editor-highlight-symbols-bg: $dn-white;
$editor-highlight-strings-fg: $dn-light_magenta;/*  [190] Strings */
$editor-highlight-strings-bg: $dn-white;
$editor-highlight-numbers-fg: $dn-light_blue;/*  [191] Numbers */
$editor-highlight-numbers-bg: $dn-white;
$editor-highlight-current-line-fg: $dn-black;/*  [182] Current line */
$editor-highlight-current-line-bg: $dn-light_gray;
$editor-highlight-cur-line-comments-fg: $dn-blue;/*  [184] Cur. line comments */
$editor-highlight-cur-line-comments-bg: $dn-light_gray;
$editor-highlight-current-line-selected-fg: $dn-light_gray;/*  [183] Current line selected */
$editor-highlight-current-line-selected-bg: $dn-blue;
$editor-highlight-current-column-fg: $dn-black;/*  [185] Current column */
$editor-highlight-current-column-bg: $dn-light_gray;

/* -- Menu ---------------------------------------------------------------- */
$editor-menu-normal-fg: $dn-black;    /*  [ 64] Normal */
$editor-menu-normal-bg: $dn-cyan;
$editor-menu-disabled-fg: $dn-light_gray;/*  [ 65] Disabled */
$editor-menu-disabled-bg: $dn-cyan;
$editor-menu-shortcut-fg: $dn-white;  /*  [ 66] Shortcut */
$editor-menu-shortcut-bg: $dn-cyan;
$editor-menu-selected-fg: $dn-white;  /*  [ 67] Selected */
$editor-menu-selected-bg: $dn-blue;
$editor-menu-selected-disabled-fg: $dn-light_gray;/*  [ 68] Selected disabled */
$editor-menu-selected-disabled-bg: $dn-blue;
$editor-menu-shortcut-selected-fg: $dn-white;/*  [ 69] Shortcut selected */
$editor-menu-shortcut-selected-bg: $dn-blue;

/* -- Disk Fixer ---------------------------------------------------------- */
$fixer-frame-passive-fg: $dn-light_gray;/*  [153] Frame passive */
$fixer-frame-passive-bg: $dn-cyan;
$fixer-frame-active-fg: $dn-black;    /*  [154] Frame active */
$fixer-frame-active-bg: $dn-cyan;
$fixer-frame-icons-fg: $dn-blue;      /*  [156] Frame icons */
$fixer-frame-icons-bg: $dn-cyan;
$fixer-frame-title-fg: $dn-white;     /*  [155] Frame title */
$fixer-frame-title-bg: $dn-blue;
$fixer-scroll-bar-page-fg: $dn-white; /*  [157] Scroll bar page */
$fixer-scroll-bar-page-bg: $dn-black;
$fixer-scroll-bar-icons-fg: $dn-white;/*  [158] Scroll bar icons */
$fixer-scroll-bar-icons-bg: $dn-black;
$fixer-normal-text-fg: $dn-black;     /*  [159] Normal text */
$fixer-normal-text-bg: $dn-white;
$fixer-selected-text-fg: $dn-white;   /*  [160] Selected text */
$fixer-selected-text-bg: $dn-blue;
$fixer-sector-title-fg: $dn-yellow;   /*  [161] Sector title */
$fixer-sector-title-bg: $dn-blue;
$fixer-edit-line-fg: $dn-dark_gray;   /*  [162] Edit line */
$fixer-edit-line-bg: $dn-white;

/* -- Menu ---------------------------------------------------------------- */
$fixer-menu-normal-fg: $dn-black;     /*  [147] Normal */
$fixer-menu-normal-bg: $dn-cyan;
$fixer-menu-disabled-fg: $dn-light_gray;/*  [148] Disabled */
$fixer-menu-disabled-bg: $dn-cyan;
$fixer-menu-shortcut-fg: $dn-white;   /*  [149] Shortcut */
$fixer-menu-shortcut-bg: $dn-cyan;
$fixer-menu-selected-fg: $dn-white;   /*  [150] Selected */
$fixer-menu-selected-bg: $dn-blue;
$fixer-menu-selected-disabled-fg: $dn-light_gray;/*  [151] Selected disabled */
$fixer-menu-selected-disabled-bg: $dn-blue;
$fixer-menu-shortcut-selected-fg: $dn-white;/*  [152] Shortcut selected */
$fixer-menu-shortcut-selected-bg: $dn-blue;

/* -- Terminal ------------------------------------------------------------ */
$terminal-frame-passive-fg: $dn-light_gray;/*  [  8] Frame passive */
$terminal-frame-passive-bg: $dn-cyan;
$terminal-frame-active-fg: $dn-black; /*  [  9] Frame active */
$terminal-frame-active-bg: $dn-cyan;
$terminal-frame-icons-fg: $dn-blue;   /*  [ 10] Frame icons */
$terminal-frame-icons-bg: $dn-cyan;
$terminal-scroll-bar-page-fg: $dn-white;/*  [ 11] Scroll bar page */
$terminal-scroll-bar-page-bg: $dn-black;
$terminal-scroll-bar-icons-fg: $dn-white;/*  [ 12] Scroll bar icons */
$terminal-scroll-bar-icons-bg: $dn-black;

/* -- dBase viewer -------------------------------------------------------- */
$dbase-frame-passive-fg: $dn-light_gray;/*  [166] Frame passive */
$dbase-frame-passive-bg: $dn-cyan;
$dbase-frame-active-fg: $dn-black;    /*  [167] Frame active */
$dbase-frame-active-bg: $dn-cyan;
$dbase-frame-icons-fg: $dn-blue;      /*  [168] Frame icons */
$dbase-frame-icons-bg: $dn-cyan;
$dbase-fields-titles-fg: $dn-white;   /*  [169] Fields titles */
$dbase-fields-titles-bg: $dn-blue;
$dbase-normal-text-fg: $dn-black;     /*  [170] Normal text */
$dbase-normal-text-bg: $dn-white;
$dbase-cursor-fg: $dn-white;          /*  [171] Cursor */
$dbase-cursor-bg: $dn-blue;

/* The rest of the .PAL, for the record. Every palette also stores where
   the cursor was in DOS Navigator's own Colors dialog when it was saved:
   group 2 of 22, items 4 0 22 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0.
   Window state rather than colour, and the group numbers name a group
   list no surviving source has -- these palettes were written by a build
   with 22 colour groups, and 1.51's DN.DNR defines 20. Carried as a
   comment so that decoding the file is not the same as discarding it. */
