/*
 * Norton Commander -- DOS Navigator's NORTON.PAL.
 *
 * Generated by tools/palconv.py; edit that, or the .PAL, not this.
 * Load it after navigator.nss, whose rules read the names below:
 *
 *     python -m navigator --theme norton
 *
 * The palette leaves the sixteen VGA colour registers alone, so the
 * colours below are named rather than pinned and the terminal's own
 * theme still decides what, say, `cyan' looks like.
 */

/* All 144 entries DOS Navigator's Colors dialog exposes, in its groups and
   its order. `>' marks the eight navigator.nss reads today; the rest are one
   rule away from being live, and are carried rather than dropped. */

/* -- Timer --------------------------------------------------------------- */
$desktop-fg: light_cyan;              /*> [  1] Color -- CBackground[1] */
$desktop-bg: blue;

/* -- Menus --------------------------------------------------------------- */
$bar-fg: black;                       /*> [  2] Normal -- CMenuView, CStatusLine[1] */
$bar-bg: cyan;
$bar-disabled-fg: dark_gray;          /*  [  3] Disabled -- CMenuView, CStatusLine[2] */
$bar-disabled-bg: cyan;
$bar-key-fg: yellow;                  /*> [  4] Shortcut -- CMenuView, CStatusLine[3] */
$bar-key-bg: cyan;
$bar-selected-fg: white;              /*  [  5] Selected -- CMenuView, CStatusLine[4] */
$bar-selected-bg: black;
$bar-selected-disabled-fg: dark_gray; /*  [  6] Selected disabled -- CMenuView, CStatusLine[5] */
$bar-selected-disabled-bg: black;
$bar-selected-key-fg: yellow;         /*  [  7] Shortcut selected -- CMenuView, CStatusLine[6] */
$bar-selected-key-bg: black;

/* -- Dialogs ------------------------------------------------------------- */
$dialog-frame-background-fg: black;   /*  [ 33] Frame/background */
$dialog-frame-background-bg: light_gray;
$dialog-frame-icons-fg: black;        /*  [ 34] Frame icons */
$dialog-frame-icons-bg: light_gray;
$dialog-scroll-bar-page-fg: cyan;     /*  [ 35] Scroll bar page */
$dialog-scroll-bar-page-bg: blue;
$dialog-scroll-bar-icons-fg: cyan;    /*  [ 36] Scroll bar icons */
$dialog-scroll-bar-icons-bg: blue;
$dialog-static-text-fg: black;        /*  [ 37] Static text */
$dialog-static-text-bg: light_gray;
$dialog-label-normal-fg: black;       /*  [ 38] Label normal */
$dialog-label-normal-bg: light_gray;
$dialog-label-selected-fg: white;     /*  [ 39] Label selected */
$dialog-label-selected-bg: light_gray;
$dialog-label-shortcut-fg: yellow;    /*  [ 40] Label shortcut */
$dialog-label-shortcut-bg: light_gray;
$dialog-button-normal-fg: light_gray; /*  [ 41] Button normal */
$dialog-button-normal-bg: black;
$dialog-button-default-fg: light_cyan;/*  [ 42] Button default */
$dialog-button-default-bg: black;
$dialog-button-selected-fg: black;    /*  [ 43] Button selected */
$dialog-button-selected-bg: cyan;
$dialog-button-disabled-fg: dark_gray;/*  [ 44] Button disabled */
$dialog-button-disabled-bg: black;
$dialog-button-shortcut-fg: yellow;   /*  [ 45] Button shortcut */
$dialog-button-shortcut-bg: black;
$dialog-shortcut-selected-fg: yellow; /*  [178] Shortcut selected */
$dialog-shortcut-selected-bg: cyan;
$dialog-shortcut-default-fg: white;   /*  [179] Shortcut default */
$dialog-shortcut-default-bg: black;
$dialog-button-shadow-fg: dark_gray;  /*  [ 46] Button shadow */
$dialog-button-shadow-bg: light_gray;
$dialog-cluster-normal-fg: black;     /*  [ 47] Cluster normal */
$dialog-cluster-normal-bg: cyan;
$dialog-cluster-selected-fg: white;   /*  [ 48] Cluster selected */
$dialog-cluster-selected-bg: cyan;
$dialog-cluster-shortcut-fg: yellow;  /*  [ 49] Cluster shortcut */
$dialog-cluster-shortcut-bg: cyan;
$dialog-input-normal-fg: black;       /*  [ 50] Input normal */
$dialog-input-normal-bg: cyan;
$dialog-input-selected-fg: cyan;      /*  [ 51] Input selected */
$dialog-input-selected-bg: black;
$dialog-input-arrow-fg: black;        /*  [ 52] Input arrow */
$dialog-input-arrow-bg: cyan;
$dialog-history-button-fg: white;     /*  [ 53] History button */
$dialog-history-button-bg: black;
$dialog-history-sides-fg: black;      /*  [ 54] History sides */
$dialog-history-sides-bg: light_gray;
$dialog-history-bar-page-fg: blue;    /*  [ 55] History bar page */
$dialog-history-bar-page-bg: cyan;
$dialog-history-bar-icons-fg: blue;   /*  [ 56] History bar icons */
$dialog-history-bar-icons-bg: cyan;
$dialog-list-normal-fg: black;        /*  [ 57] List normal */
$dialog-list-normal-bg: cyan;
$dialog-list-focused-fg: cyan;        /*  [ 58] List focused */
$dialog-list-focused-bg: black;
$dialog-list-selected-fg: blue;       /*  [ 59] List selected */
$dialog-list-selected-bg: cyan;
$dialog-list-divider-fg: blue;        /*  [ 60] List divider */
$dialog-list-divider-bg: cyan;
$dialog-information-pane-fg: cyan;    /*  [ 61] Information pane */
$dialog-information-pane-bg: black;

/* -- Tree ---------------------------------------------------------------- */
$dialog-tree-normal-tree-fg: white;   /*  [104] Normal tree */
$dialog-tree-normal-tree-bg: cyan;
$dialog-tree-normal-nodes-fg: white;  /*  [105] Normal nodes */
$dialog-tree-normal-nodes-bg: cyan;
$dialog-tree-selected-node-fg: white; /*  [106] Selected node */
$dialog-tree-selected-node-bg: black;
$dialog-tree-default-node-fg: yellow; /*  [107] Default node */
$dialog-tree-default-node-bg: cyan;
$dialog-tree-selected-default-fg: yellow;/*  [108] Selected default */
$dialog-tree-selected-default-bg: black;
$dialog-tree-selected-passive-fg: blue;/*  [109] Selected passive */
$dialog-tree-selected-passive-bg: cyan;
$dialog-tree-selected-def-passive-fg: blue;/*  [110] Selected def. passive */
$dialog-tree-selected-def-passive-bg: cyan;

/* -- File Manager -------------------------------------------------------- */
$frame-fg: light_gray;                /*  [ 80] Frame passive -- CDoubleWindow[1] -> CFrame[1,2] */
$frame-bg: blue;
$active-frame-fg: light_cyan;         /*  [ 81] Frame active -- CDoubleWindow[2] -> CFrame[3,4] */
$active-frame-bg: blue;
$frame-icon-fg: light_cyan;           /*  [ 82] Frame icons -- CDoubleWindow[3] -> CFrame[5] */
$frame-icon-bg: blue;
$scrollbar-page-fg: light_cyan;       /*  [ 83] Scroll bar page -- CDoubleWindow[4] -> CScrollBar[1] */
$scrollbar-page-bg: blue;
$scrollbar-arrow-fg: light_cyan;      /*  [ 84] Scroll bar icons -- CDoubleWindow[5] -> CScrollBar[2,3] */
$scrollbar-arrow-bg: blue;

/* -- File Panel ---------------------------------------------------------- */
$panel-fg: light_cyan;                /*> [ 85] Normal text -- CDoubleWindow[6] -> CPanel[1] */
$panel-bg: blue;
$marked-fg: yellow;                   /*  [ 87] Selected text -- CDoubleWindow[8] -> CPanel[3] */
$marked-bg: blue;
$cursor-fg: black;                    /*> [ 88] Normal cursor -- CDoubleWindow[9] -> CPanel[4] */
$cursor-bg: cyan;
$marked-cursor-fg: yellow;            /*  [ 89] Selected cursor -- CDoubleWindow[10] -> CPanel[5] */
$marked-cursor-bg: cyan;
$divider-fg: light_cyan;              /*  [ 86] List divider -- CDoubleWindow[7] -> CPanel[2] */
$divider-bg: blue;
$active-title-fg: black;              /*> [ 90] Directory active -- CDoubleWindow[11] -> CTopView[1] */
$active-title-bg: cyan;
$title-fg: light_cyan;                /*> [ 91] Directory passive -- CDoubleWindow[12] -> CTopView[2] */
$title-bg: blue;
$column-title-fg: yellow;             /*  [165] Column title -- CDoubleWindow[32] -> CPanel[6] */
$column-title-bg: blue;

/* -- Highlight ----------------------------------------------------------- */
$directory-fg: white;                 /*> [172] Directories -- CDoubleWindow[33] -> CPanel[7], ttDirectory */
$directory-bg: blue;
$executable-fg: light_green;          /*  [173] Executables -- CDoubleWindow[34] -> CPanel[8], ttExec */
$executable-bg: blue;
$archive-fg: light_red;               /*  [174] Archives -- CDoubleWindow[35] -> CPanel[9], ttArc */
$archive-bg: blue;
$highlight-custom-1-fg: light_green;  /*  [175] Custom 1 */
$highlight-custom-1-bg: blue;
$highlight-custom-2-fg: light_red;    /*  [176] Custom 2 */
$highlight-custom-2-bg: blue;
$highlight-custom-3-fg: light_gray;   /*  [177] Custom 3 */
$highlight-custom-3-bg: blue;
$highlight-custom-4-fg: light_magenta;/*  [180] Custom 4 */
$highlight-custom-4-bg: blue;
$highlight-custom-5-fg: white;        /*  [181] Custom 5 */
$highlight-custom-5-bg: blue;

/* -- Drive Line ---------------------------------------------------------- */
$drive-line-drive-letters-fg: light_cyan;/*  [186] Drive letters */
$drive-line-drive-letters-bg: blue;
$drive-line-drive-selected-fg: yellow;/*  [188] Drive selected */
$drive-line-drive-selected-bg: blue;
$drive-line-frame-fg: light_cyan;     /*  [187] Frame */
$drive-line-frame-bg: blue;

/* -- Info ---------------------------------------------------------------- */
$info-current-file-fg: light_cyan;    /*  [119] Current file */
$info-current-file-bg: blue;
$info-selected-text-fg: yellow;       /*  [120] Selected text */
$info-selected-text-bg: blue;
$info-selected-numbers-fg: yellow;    /*  [121] Selected numbers */
$info-selected-numbers-bg: blue;
$info-totals-text-fg: light_cyan;     /*  [122] Totals text */
$info-totals-text-bg: blue;
$info-totals-numbers-fg: yellow;      /*  [123] Totals numbers */
$info-totals-numbers-bg: blue;
$info-free-space-text-fg: light_cyan; /*  [124] Free space text */
$info-free-space-text-bg: blue;
$info-free-space-numbers-fg: yellow;  /*  [125] Free space numbers */
$info-free-space-numbers-bg: blue;

/* -- Tree ---------------------------------------------------------------- */
$tree-normal-tree-fg: light_cyan;     /*  [ 94] Normal tree */
$tree-normal-tree-bg: blue;
$tree-normal-nodes-fg: light_cyan;    /*  [ 95] Normal nodes */
$tree-normal-nodes-bg: blue;
$tree-selected-node-fg: black;        /*  [ 96] Selected node */
$tree-selected-node-bg: cyan;
$tree-default-node-fg: yellow;        /*  [ 97] Default node */
$tree-default-node-bg: blue;
$tree-selected-default-fg: yellow;    /*  [ 98] Selected default */
$tree-selected-default-bg: cyan;
$tree-selected-passive-fg: light_gray;/*  [ 99] Selected passive */
$tree-selected-passive-bg: blue;
$tree-selected-def-passive-fg: light_gray;/*  [100] Selected def. passive */
$tree-selected-def-passive-bg: blue;
$tree-info-box-fg: yellow;            /*  [101] Info box */
$tree-info-box-bg: blue;

/* -- Quick View ---------------------------------------------------------- */
$quick-view-normal-text-fg: light_cyan;/*  [ 92] Normal text */
$quick-view-normal-text-bg: blue;
$quick-view-selected-text-fg: yellow; /*  [ 93] Selected text */
$quick-view-selected-text-bg: blue;

/* -- Disk Info ----------------------------------------------------------- */
$disk-info-normal-text-fg: light_cyan;/*  [103] Normal text */
$disk-info-normal-text-bg: blue;
$disk-info-highlighted-text-fg: yellow;/*  [102] Highlighted text */
$disk-info-highlighted-text-bg: blue;

/* -- File Viewer --------------------------------------------------------- */
$viewer-frame-passive-fg: light_gray; /*  [112] Frame passive */
$viewer-frame-passive-bg: blue;
$viewer-frame-active-fg: light_cyan;  /*  [113] Frame active */
$viewer-frame-active-bg: blue;
$viewer-frame-icons-fg: white;        /*  [114] Frame icons */
$viewer-frame-icons-bg: blue;
$viewer-scroll-bar-page-fg: light_cyan;/*  [115] Scroll bar page */
$viewer-scroll-bar-page-bg: blue;
$viewer-scroll-bar-icons-fg: white;   /*  [116] Scroll bar icons */
$viewer-scroll-bar-icons-bg: blue;
$viewer-normal-text-fg: light_cyan;   /*  [117] Normal text */
$viewer-normal-text-bg: blue;
$viewer-selected-text-fg: black;      /*  [118] Selected text */
$viewer-selected-text-bg: cyan;

/* -- Editor/Spreadsheet -------------------------------------------------- */
$editor-frame-passive-fg: light_gray; /*  [ 70] Frame passive */
$editor-frame-passive-bg: blue;
$editor-frame-active-fg: light_cyan;  /*  [ 71] Frame active */
$editor-frame-active-bg: blue;
$editor-frame-icons-fg: white;        /*  [ 73] Frame icons */
$editor-frame-icons-bg: blue;
$editor-frame-title-fg: yellow;       /*  [ 72] Frame title */
$editor-frame-title-bg: blue;
$editor-scroll-bar-page-fg: light_cyan;/*  [ 74] Scroll bar page */
$editor-scroll-bar-page-bg: blue;
$editor-scroll-bar-icons-fg: white;   /*  [ 75] Scroll bar icons */
$editor-scroll-bar-icons-bg: blue;
$editor-normal-text-fg: light_cyan;   /*  [ 76] Normal text */
$editor-normal-text-bg: blue;
$editor-selected-text-fg: black;      /*  [ 77] Selected text */
$editor-selected-text-bg: cyan;

/* -- Highlight ----------------------------------------------------------- */
$editor-highlight-comments-fg: cyan;  /*  [164] Comments */
$editor-highlight-comments-bg: blue;
$editor-highlight-symbols-fg: white;  /*  [189] Symbols */
$editor-highlight-symbols-bg: blue;
$editor-highlight-strings-fg: light_red;/*  [190] Strings */
$editor-highlight-strings-bg: blue;
$editor-highlight-numbers-fg: light_green;/*  [191] Numbers */
$editor-highlight-numbers-bg: blue;
$editor-highlight-current-line-fg: white;/*  [182] Current line */
$editor-highlight-current-line-bg: blue;
$editor-highlight-cur-line-comments-fg: white;/*  [184] Cur. line comments */
$editor-highlight-cur-line-comments-bg: blue;
$editor-highlight-current-line-selected-fg: white;/*  [183] Current line selected */
$editor-highlight-current-line-selected-bg: cyan;
$editor-highlight-current-column-fg: white;/*  [185] Current column */
$editor-highlight-current-column-bg: cyan;

/* -- Menu ---------------------------------------------------------------- */
$editor-menu-normal-fg: black;        /*  [ 64] Normal */
$editor-menu-normal-bg: cyan;
$editor-menu-disabled-fg: dark_gray;  /*  [ 65] Disabled */
$editor-menu-disabled-bg: cyan;
$editor-menu-shortcut-fg: yellow;     /*  [ 66] Shortcut */
$editor-menu-shortcut-bg: cyan;
$editor-menu-selected-fg: white;      /*  [ 67] Selected */
$editor-menu-selected-bg: black;
$editor-menu-selected-disabled-fg: dark_gray;/*  [ 68] Selected disabled */
$editor-menu-selected-disabled-bg: black;
$editor-menu-shortcut-selected-fg: yellow;/*  [ 69] Shortcut selected */
$editor-menu-shortcut-selected-bg: black;

/* -- Disk Fixer ---------------------------------------------------------- */
$fixer-frame-passive-fg: light_gray;  /*  [153] Frame passive */
$fixer-frame-passive-bg: blue;
$fixer-frame-active-fg: light_cyan;   /*  [154] Frame active */
$fixer-frame-active-bg: blue;
$fixer-frame-icons-fg: light_cyan;    /*  [156] Frame icons */
$fixer-frame-icons-bg: blue;
$fixer-frame-title-fg: light_cyan;    /*  [155] Frame title */
$fixer-frame-title-bg: blue;
$fixer-scroll-bar-page-fg: light_cyan;/*  [157] Scroll bar page */
$fixer-scroll-bar-page-bg: blue;
$fixer-scroll-bar-icons-fg: light_cyan;/*  [158] Scroll bar icons */
$fixer-scroll-bar-icons-bg: blue;
$fixer-normal-text-fg: light_cyan;    /*  [159] Normal text */
$fixer-normal-text-bg: blue;
$fixer-selected-text-fg: black;       /*  [160] Selected text */
$fixer-selected-text-bg: cyan;
$fixer-sector-title-fg: yellow;       /*  [161] Sector title */
$fixer-sector-title-bg: blue;
$fixer-edit-line-fg: white;           /*  [162] Edit line */
$fixer-edit-line-bg: cyan;

/* -- Menu ---------------------------------------------------------------- */
$fixer-menu-normal-fg: black;         /*  [147] Normal */
$fixer-menu-normal-bg: cyan;
$fixer-menu-disabled-fg: dark_gray;   /*  [148] Disabled */
$fixer-menu-disabled-bg: cyan;
$fixer-menu-shortcut-fg: yellow;      /*  [149] Shortcut */
$fixer-menu-shortcut-bg: cyan;
$fixer-menu-selected-fg: white;       /*  [150] Selected */
$fixer-menu-selected-bg: black;
$fixer-menu-selected-disabled-fg: light_gray;/*  [151] Selected disabled */
$fixer-menu-selected-disabled-bg: black;
$fixer-menu-shortcut-selected-fg: yellow;/*  [152] Shortcut selected */
$fixer-menu-shortcut-selected-bg: black;

/* -- Terminal ------------------------------------------------------------ */
$terminal-frame-passive-fg: light_gray;/*  [  8] Frame passive */
$terminal-frame-passive-bg: black;
$terminal-frame-active-fg: white;     /*  [  9] Frame active */
$terminal-frame-active-bg: black;
$terminal-frame-icons-fg: white;      /*  [ 10] Frame icons */
$terminal-frame-icons-bg: black;
$terminal-scroll-bar-page-fg: white;  /*  [ 11] Scroll bar page */
$terminal-scroll-bar-page-bg: black;
$terminal-scroll-bar-icons-fg: white; /*  [ 12] Scroll bar icons */
$terminal-scroll-bar-icons-bg: black;

/* -- dBase viewer -------------------------------------------------------- */
$dbase-frame-passive-fg: light_gray;  /*  [166] Frame passive */
$dbase-frame-passive-bg: blue;
$dbase-frame-active-fg: light_cyan;   /*  [167] Frame active */
$dbase-frame-active-bg: blue;
$dbase-frame-icons-fg: light_cyan;    /*  [168] Frame icons */
$dbase-frame-icons-bg: blue;
$dbase-fields-titles-fg: black;       /*  [169] Fields titles */
$dbase-fields-titles-bg: cyan;
$dbase-normal-text-fg: light_cyan;    /*  [170] Normal text */
$dbase-normal-text-bg: blue;
$dbase-cursor-fg: white;              /*  [171] Cursor */
$dbase-cursor-bg: black;

/* The rest of the .PAL, for the record. Every palette also stores where
   the cursor was in DOS Navigator's own Colors dialog when it was saved:
   group 0 of 22, items 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0.
   Window state rather than colour, and the group numbers name a group
   list no surviving source has -- these palettes were written by a build
   with 22 colour groups, and 1.51's DN.DNR defines 20. Carried as a
   comment so that decoding the file is not the same as discarding it. */
