/*
 * Norton Commander -- DOS Navigator's NORTON.PAL.
 *
 * Generated by tools/palconv.py; edit that, or the .PAL, not this.
 * Load it after navigator.nss, which declares every name below:
 *
 *     python -m navigator --theme norton
 *
 * The palette leaves the sixteen VGA colour registers alone, so the
 * colours below are named rather than pinned and the terminal's own
 * theme still decides what, say, `cyan' looks like.
 */

/* What the rules in navigator.nss read. */
/* [  1] CBackground[1] */
$desktop-fg: light_cyan;
$desktop-bg: blue;
/* [  2] CMenuView/CStatusLine[1] normal text */
$bar-fg: black;
$bar-bg: cyan;
/* [  4] CMenuView/CStatusLine[3] shortcut */
$bar-key-fg: yellow;
$bar-key-bg: cyan;
/* [ 85] CDoubleWindow[6] -> CPanel[1] normal text */
$panel-fg: light_cyan;
$panel-bg: blue;
/* [ 88] CDoubleWindow[9] -> CPanel[4] cursor */
$cursor-fg: black;
$cursor-bg: cyan;
/* [ 90] CDoubleWindow[11] -> CTopView[1] focused */
$active-title-fg: black;
$active-title-bg: cyan;
/* [ 91] CDoubleWindow[12] -> CTopView[2] unfocused */
$title-fg: light_cyan;
$title-bg: blue;
/* [172] CDoubleWindow[33] -> CPanel[7] ttDirectory */
$directory-fg: white;
$directory-bg: blue;

/* Decoded from the same palette, and read by nothing yet.  Each is one
   rule away from being live, so they are carried rather than dropped. */
/* [  3] CMenuView/CStatusLine[2] */
$bar-disabled-fg: dark_gray;
$bar-disabled-bg: cyan;
/* [  5] CMenuView/CStatusLine[4] */
$bar-selected-fg: white;
$bar-selected-bg: black;
/* [  6] CMenuView/CStatusLine[5] */
$bar-selected-disabled-fg: dark_gray;
$bar-selected-disabled-bg: black;
/* [  7] CMenuView/CStatusLine[6] */
$bar-selected-key-fg: yellow;
$bar-selected-key-bg: black;
/* [ 80] CDoubleWindow[1] -> CFrame[1,2] passive */
$frame-fg: light_gray;
$frame-bg: blue;
/* [ 81] CDoubleWindow[2] -> CFrame[3,4] active */
$active-frame-fg: light_cyan;
$active-frame-bg: blue;
/* [ 82] CDoubleWindow[3] -> CFrame[5] */
$frame-icon-fg: light_cyan;
$frame-icon-bg: blue;
/* [ 83] CDoubleWindow[4] -> CScrollBar[1] */
$scrollbar-page-fg: light_cyan;
$scrollbar-page-bg: blue;
/* [ 84] CDoubleWindow[5] -> CScrollBar[2,3] */
$scrollbar-arrow-fg: light_cyan;
$scrollbar-arrow-bg: blue;
/* [ 86] CDoubleWindow[7] -> CPanel[2] column divider */
$divider-fg: light_cyan;
$divider-bg: blue;
/* [ 87] CDoubleWindow[8] -> CPanel[3] tagged file */
$marked-fg: yellow;
$marked-bg: blue;
/* [ 89] CDoubleWindow[10] -> CPanel[5] */
$marked-cursor-fg: yellow;
$marked-cursor-bg: cyan;
/* [173] CDoubleWindow[34] -> CPanel[8] ttExec */
$executable-fg: light_green;
$executable-bg: blue;
/* [174] CDoubleWindow[35] -> CPanel[9] ttArc */
$archive-fg: light_red;
$archive-bg: blue;
