/*
 * PCTools/Norton Utilities -- DOS Navigator's PCTOOLS.PAL.
 *
 * Generated by tools/palconv.py; edit that, or the .PAL, not this.
 * Load it after navigator.nss, which declares every name below:
 *
 *     python -m navigator --theme pctools
 *
 * This palette reprograms the sixteen VGA colour registers, so the
 * sixteen names are pinned to the values it asks for rather than
 * left to the terminal's own theme.  That is the whole difference
 * between it and a palette that only rearranges attributes.
 */

/* The adapter's colour registers, six bits per channel widened to eight. */
$dn-black: #000000;
$dn-blue: #0000aa;
$dn-green: #00aa00;
$dn-cyan: #00aaaa;
$dn-red: #fb0000;
$dn-magenta: #aa00aa;
$dn-brown: #aa5500;
$dn-light_gray: #aaaaaa;
$dn-dark_gray: #555555;
$dn-light_blue: #5555ca;
$dn-light_green: #55ff55;
$dn-light_cyan: #55ffff;
$dn-light_red: #ff5555;
$dn-light_magenta: #ff55ff;
$dn-yellow: #ffff00;
$dn-white: #ffffff;

/* What the rules in navigator.nss read. */
/* [  1] CBackground[1] */
$desktop-fg: $dn-black;
$desktop-bg: $dn-light_gray;
/* [  2] CMenuView/CStatusLine[1] normal text */
$bar-fg: $dn-black;
$bar-bg: $dn-white;
/* [  4] CMenuView/CStatusLine[3] shortcut */
$bar-key-fg: $dn-red;
$bar-key-bg: $dn-white;
/* [ 85] CDoubleWindow[6] -> CPanel[1] normal text */
$panel-fg: $dn-light_cyan;
$panel-bg: $dn-light_blue;
/* [ 88] CDoubleWindow[9] -> CPanel[4] cursor */
$cursor-fg: $dn-white;
$cursor-bg: $dn-black;
/* [ 90] CDoubleWindow[11] -> CTopView[1] focused */
$active-title-fg: $dn-black;
$active-title-bg: $dn-white;
/* [ 91] CDoubleWindow[12] -> CTopView[2] unfocused */
$title-fg: $dn-white;
$title-bg: $dn-light_blue;
/* [172] CDoubleWindow[33] -> CPanel[7] ttDirectory */
$directory-fg: $dn-white;
$directory-bg: $dn-light_blue;

/* Decoded from the same palette, and read by nothing yet.  Each is one
   rule away from being live, so they are carried rather than dropped. */
/* [  3] CMenuView/CStatusLine[2] */
$bar-disabled-fg: $dn-light_gray;
$bar-disabled-bg: $dn-white;
/* [  5] CMenuView/CStatusLine[4] */
$bar-selected-fg: $dn-white;
$bar-selected-bg: $dn-black;
/* [  6] CMenuView/CStatusLine[5] */
$bar-selected-disabled-fg: $dn-light_gray;
$bar-selected-disabled-bg: $dn-black;
/* [  7] CMenuView/CStatusLine[6] */
$bar-selected-key-fg: $dn-red;
$bar-selected-key-bg: $dn-black;
/* [ 80] CDoubleWindow[1] -> CFrame[1,2] passive */
$frame-fg: $dn-light_gray;
$frame-bg: $dn-light_blue;
/* [ 81] CDoubleWindow[2] -> CFrame[3,4] active */
$active-frame-fg: $dn-white;
$active-frame-bg: $dn-light_blue;
/* [ 82] CDoubleWindow[3] -> CFrame[5] */
$frame-icon-fg: $dn-yellow;
$frame-icon-bg: $dn-light_blue;
/* [ 83] CDoubleWindow[4] -> CScrollBar[1] */
$scrollbar-page-fg: $dn-white;
$scrollbar-page-bg: $dn-light_blue;
/* [ 84] CDoubleWindow[5] -> CScrollBar[2,3] */
$scrollbar-arrow-fg: $dn-white;
$scrollbar-arrow-bg: $dn-light_blue;
/* [ 86] CDoubleWindow[7] -> CPanel[2] column divider */
$divider-fg: $dn-white;
$divider-bg: $dn-light_blue;
/* [ 87] CDoubleWindow[8] -> CPanel[3] tagged file */
$marked-fg: $dn-yellow;
$marked-bg: $dn-light_blue;
/* [ 89] CDoubleWindow[10] -> CPanel[5] */
$marked-cursor-fg: $dn-yellow;
$marked-cursor-bg: $dn-black;
/* [173] CDoubleWindow[34] -> CPanel[8] ttExec */
$executable-fg: $dn-white;
$executable-bg: $dn-light_blue;
/* [174] CDoubleWindow[35] -> CPanel[9] ttArc */
$archive-fg: $dn-light_green;
$archive-bg: $dn-light_blue;
