/*
 * VGA Default color palette for Mono VGA monitors -- DOS Navigator's _BW.PAL.
 *
 * Generated by tools/palconv.py; edit that, or the .PAL, not this.
 * Load it after navigator.nss, which declares every name below:
 *
 *     python -m navigator --theme vga-bw
 *
 * This palette reprograms the sixteen VGA colour registers, so the
 * sixteen names are pinned to the values it asks for rather than
 * left to the terminal's own theme.  That is the whole difference
 * between it and a palette that only rearranges attributes.
 */

/* The adapter's colour registers, six bits per channel widened to eight. */
$dn-black: #000000;
$dn-blue: #393939;
$dn-green: #393939;
$dn-cyan: #717171;
$dn-red: #393939;
$dn-magenta: #717171;
$dn-brown: #555555;
$dn-light_gray: #aaaaaa;
$dn-dark_gray: #555555;
$dn-light_blue: #8e8e8e;
$dn-light_green: #8e8e8e;
$dn-light_cyan: #c6c6c6;
$dn-light_red: #8e8e8e;
$dn-light_magenta: #c6c6c6;
$dn-yellow: #c6c6c6;
$dn-white: #ffffff;

/* What the rules in navigator.nss read. */
/* [  1] CBackground[1] */
$desktop-fg: $dn-blue;
$desktop-bg: $dn-light_gray;
/* [  2] CMenuView/CStatusLine[1] normal text */
$bar-fg: $dn-black;
$bar-bg: $dn-light_gray;
/* [  4] CMenuView/CStatusLine[3] shortcut */
$bar-key-fg: $dn-red;
$bar-key-bg: $dn-light_gray;
/* [ 85] CDoubleWindow[6] -> CPanel[1] normal text */
$panel-fg: $dn-light_gray;
$panel-bg: $dn-dark_gray;
/* [ 88] CDoubleWindow[9] -> CPanel[4] cursor */
$cursor-fg: $dn-black;
$cursor-bg: $dn-cyan;
/* [ 90] CDoubleWindow[11] -> CTopView[1] focused */
$active-title-fg: $dn-white;
$active-title-bg: $dn-cyan;
/* [ 91] CDoubleWindow[12] -> CTopView[2] unfocused */
$title-fg: $dn-white;
$title-bg: $dn-dark_gray;
/* [172] CDoubleWindow[33] -> CPanel[7] ttDirectory */
$directory-fg: $dn-white;
$directory-bg: $dn-dark_gray;

/* Decoded from the same palette, and read by nothing yet.  Each is one
   rule away from being live, so they are carried rather than dropped. */
/* [  3] CMenuView/CStatusLine[2] */
$bar-disabled-fg: $dn-dark_gray;
$bar-disabled-bg: $dn-light_gray;
/* [  5] CMenuView/CStatusLine[4] */
$bar-selected-fg: $dn-black;
$bar-selected-bg: $dn-green;
/* [  6] CMenuView/CStatusLine[5] */
$bar-selected-disabled-fg: $dn-dark_gray;
$bar-selected-disabled-bg: $dn-green;
/* [  7] CMenuView/CStatusLine[6] */
$bar-selected-key-fg: $dn-red;
$bar-selected-key-bg: $dn-green;
/* [ 80] CDoubleWindow[1] -> CFrame[1,2] passive */
$frame-fg: $dn-light_gray;
$frame-bg: $dn-dark_gray;
/* [ 81] CDoubleWindow[2] -> CFrame[3,4] active */
$active-frame-fg: $dn-white;
$active-frame-bg: $dn-dark_gray;
/* [ 82] CDoubleWindow[3] -> CFrame[5] */
$frame-icon-fg: $dn-light_cyan;
$frame-icon-bg: $dn-dark_gray;
/* [ 83] CDoubleWindow[4] -> CScrollBar[1] */
$scrollbar-page-fg: $dn-white;
$scrollbar-page-bg: $dn-dark_gray;
/* [ 84] CDoubleWindow[5] -> CScrollBar[2,3] */
$scrollbar-arrow-fg: $dn-black;
$scrollbar-arrow-bg: $dn-white;
/* [ 86] CDoubleWindow[7] -> CPanel[2] column divider */
$divider-fg: $dn-white;
$divider-bg: $dn-dark_gray;
/* [ 87] CDoubleWindow[8] -> CPanel[3] tagged file */
$marked-fg: $dn-yellow;
$marked-bg: $dn-dark_gray;
/* [ 89] CDoubleWindow[10] -> CPanel[5] */
$marked-cursor-fg: $dn-yellow;
$marked-cursor-bg: $dn-cyan;
/* [173] CDoubleWindow[34] -> CPanel[8] ttExec */
$executable-fg: $dn-light_cyan;
$executable-bg: $dn-dark_gray;
/* [174] CDoubleWindow[35] -> CPanel[9] ttArc */
$archive-fg: $dn-light_green;
$archive-bg: $dn-dark_gray;
